'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {validatePatch}=require('../src/patch');
function oneLine(file){return `diff --git a/${file} b/${file}\n--- a/${file}\n+++ b/${file}\n@@ -1 +1 @@\n-a\n+b\n`;}
test('accepts normal textual patch',()=>{const v=validatePatch(oneLine('src/a.js'));assert.ok(v.paths.includes('src/a.js'));});
test('Git numstat path parsing preserves spaces and quoted unicode paths',()=>{const spaced=validatePatch('diff --git a/file with space.txt b/file with space.txt\n--- a/file with space.txt\t\n+++ b/file with space.txt\t\n@@ -1 +1 @@\n-a\n+b\n');assert.deepEqual(spaced.paths,['file with space.txt']);const unicode=validatePatch('diff --git "a/\\344\\270\\255\\346\\226\\207.txt" "b/\\344\\270\\255\\346\\226\\207.txt"\n--- "a/\\344\\270\\255\\346\\226\\207.txt"\n+++ "b/\\344\\270\\255\\346\\226\\207.txt"\n@@ -1 +1 @@\n-a\n+b\n');assert.deepEqual(unicode.paths,['中文.txt']);});
test('rejects rename and copy patches because rollback must snapshot every mutated path',()=>{assert.throws(()=>validatePatch('diff --git a/old.txt b/new.txt\nsimilarity index 100%\nrename from old.txt\nrename to new.txt\n'),/Rename\/copy patches are not allowed/);});
test('rejects path traversal',()=>{assert.throws(()=>validatePatch(oneLine('../x')),error=>['EPATCHPATH','EPATCHFORMAT'].includes(error.code));});
test('rejects Safe Core and private Debug state mutation',()=>{assert.throws(()=>validatePatch(oneLine('src/codex-safe-core/x')),error=>error.code==='EPATCHPATH');assert.throws(()=>validatePatch(oneLine('.codex-debug/sessions/x')),error=>error.code==='EPATCHPATH');});
test('rejects protected control-plane secret generated and vendor paths',()=>{for(const file of ['.github/workflows/ci.yml','.github/actions/custom/action.yml','.gitmodules','CODEOWNERS','.env','.env.production','certs/client.key','vendor/lib/a.c','third_party/lib/a.c','generated/api.js','build/output.js','dist/app.js','node_modules/pkg/index.js'])assert.throws(()=>validatePatch(oneLine(file)),error=>error.code==='EPATCHPROTECTED',file);});
