'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const corpus=require('../quality/promotion-corpus.json');
const policy=require('../quality/promotion-admission-policy.json');
const {stableDigest,createRecord}=require('../scripts/model-evaluation');
const {promotionReadiness,toEvaluationCorpus}=require('../scripts/promotion-corpus');
const {GITHUB_ACTIONS_INTEGRATION_ID,createGovernanceLock,evaluateGovernance}=require('../scripts/promotion-repository-governance');
const {ADMISSION_VERSION,validateAdmissionPolicy,evaluateAdmission}=require('../scripts/promotion-admission');

const REPO='jiying2007/codex-debug';
function clone(value){return JSON.parse(JSON.stringify(value));}
function phase(tokens=10){return {model:'gpt-test',codexVersion:'0.0.0-test',providerMode:'openai',runtimeSource:'test',modelEvidenceDigest:'',usage:{inputTokens:tokens,outputTokens:0,totalTokens:tokens,cachedInputTokens:0},requestEstimate:null,durationMs:1};}
function runContext(debugCommit,runId='42'){return {workflow:'Promotion Model Evaluation',runId,runAttempt:'1',event:'workflow_dispatch',repository:REPO,sourceSha:debugCommit};}
function qualificationFor(reviewed,{debugCommit='a'.repeat(40),coreCommit='b'.repeat(40),runId='42'}={}){
  const record={schemaVersion:1,kind:'codex-debug-promotion-corpus-qualification',recordedAt:'2026-09-06T00:00:00.000Z',debugCommit,coreCommit,corpusDigest:stableDigest(reviewed),readiness:promotionReadiness(reviewed),runContext:runContext(debugCommit,runId),cases:reviewed.cases.map(item=>({caseId:item.id,repository:item.repository,anchorRef:item.anchorRef,badCommit:item.badCommit,fixedCommit:item.fixedCommit,commandDigest:stableDigest(item.reproduction.command),badSummary:{runs:1,failures:1,timeouts:0,reproducibleFailure:true},fixedSummary:{runs:1,failures:0,timeouts:0,reproducibleFailure:false},badRepresentativeDigest:stableDigest(`bad:${item.id}`),fixedRepresentativeDigest:stableDigest(`fixed:${item.id}`),transitionDigest:stableDigest(`transition:${item.id}`)}))};
  record.digest=stableDigest(record);return record;
}
function liveRecordFor(reviewed,{debugCommit='a'.repeat(40),coreCommit='b'.repeat(40),runId='42',promotionEligible=false,tokens=10}={}){
  const evalCorpus=toEvaluationCorpus(reviewed),cases=evalCorpus.cases.map(spec=>{const terms=spec.expected.rootCauseTerms||[],text=terms.length?terms.join(' '):'insufficient evidence';return {caseId:spec.id,evidenceDigest:stableDigest(`evidence:${spec.id}`),expectationDigest:spec.expectationDigest,judgment:{rootCauseText:text,rootCauseDigest:stableDigest(text),causalAssessment:spec.expected.assessment,patchProposed:false,patchDisposition:'none',patchApplicable:null,supportedHypotheses:terms.length?[text]:[]},execution:{hypothesis:phase(tokens),causalVerification:phase(tokens)}};});
  const base=createRecord({source:'live',promotionEligible,debugCommit,coreCommit,corpus:evalCorpus,cases,recordedAt:'2026-09-06T00:01:00.000Z'}),copy={...base};delete copy.recordDigest;copy.runContext=runContext(debugCommit,runId);copy.recordDigest=stableDigest(copy);return copy;
}
function ruleset(){return {id:123,name:'codex-debug-main-promotion-governance',target:'branch',source_type:'Repository',source:REPO,enforcement:'active',created_at:'2026-09-07T00:00:00Z',updated_at:'2026-09-07T00:01:00Z',bypass_actors:[],conditions:{ref_name:{include:['refs/heads/main'],exclude:[]}},rules:[{type:'deletion'},{type:'non_fast_forward'},{type:'pull_request',parameters:{dismiss_stale_reviews_on_push:true,required_approving_review_count:0}},{type:'required_status_checks',parameters:{strict_required_status_checks_policy:true,required_status_checks:[{context:'CI Gate',integration_id:GITHUB_ACTIONS_INTEGRATION_ID}]}}]};}
function governanceFor({debugCommit='a'.repeat(40),runId='42'}={}){
  const full=ruleset(),governanceLock=createGovernanceLock({repository:REPO,branch:'main',requiredCheck:'CI Gate',ruleset:full,reviewedAt:'2026-09-07T00:02:00.000Z'}),live=clone(full);delete live.bypass_actors;
  const governanceReceipt=evaluateGovernance({repository:REPO,branch:'main',sourceSha:debugCommit,rulesets:[live],lock:governanceLock,recordedAt:'2026-09-07T00:03:00.000Z',runContext:runContext(debugCommit,runId)});
  assert.equal(governanceReceipt.ready,true);return {governanceLock,governanceReceipt};
}
function calibrationEvidenceFor(reviewed,{debugCommit='c'.repeat(40),coreCommit='b'.repeat(40),runId='40'}={}){return {reportDigest:'d'.repeat(64),debugCommit,coreCommit,corpusDigest:stableDigest(reviewed),evaluationCorpusDigest:stableDigest(toEvaluationCorpus(reviewed)),qualificationDigest:'e'.repeat(64),modelRecordDigest:'f'.repeat(64),admissionDigest:'1'.repeat(64),runContext:runContext(debugCommit,runId)};}
function reviewedPolicy(reviewed=corpus,{coreCommit='b'.repeat(40)}={}){const value=clone(policy);value.reviewed=true;value.calibrationEvidence=calibrationEvidenceFor(reviewed,{coreCommit});value.quality.minimumAssessmentAccuracy=1;value.quality.minimumRootCauseTop1Accuracy=1;value.quality.minimumInsufficientEvidenceAccuracy=1;value.tokenEfficiency={calibrated:true,maximumTokensPerCase:100};const body={...value};delete body.policyDigest;value.policyDigest=stableDigest(body);return value;}

test('checked-in admission policy is digest-bound, unreviewed and has no invented calibration evidence',()=>{validateAdmissionPolicy(policy);assert.equal(policy.reviewed,false);assert.equal(policy.calibrationEvidence,null);assert.equal(policy.tokenEfficiency.calibrated,false);assert.equal(policy.tokenEfficiency.maximumTokensPerCase,null);assert.equal(policy.safety.maximumFalseSupport,0);assert.equal(policy.safety.maximumFalseFixCandidates,0);assert.equal(policy.safety.maximumPatchPolicyViolations,0);});

test('reviewed policy cannot exist without a bound calibration report provenance record',()=>{const changed=clone(policy);changed.reviewed=true;changed.quality.minimumAssessmentAccuracy=1;changed.quality.minimumRootCauseTop1Accuracy=1;changed.tokenEfficiency={calibrated:true,maximumTokensPerCase:100};const body={...changed};delete body.policyDigest;changed.policyDigest=stableDigest(body);assert.throws(()=>validateAdmissionPolicy(changed),/requires calibrationEvidence/);});

test('reviewed policy calibration evidence must be a workflow-dispatch Promotion Model Evaluation record',()=>{const changed=reviewedPolicy();changed.calibrationEvidence.runContext.event='push';let body={...changed};delete body.policyDigest;changed.policyDigest=stableDigest(body);assert.throws(()=>validateAdmissionPolicy(changed),/must come from workflow_dispatch/);const changed2=reviewedPolicy();changed2.calibrationEvidence.runContext.sourceSha='9'.repeat(40);body={...changed2};delete body.policyDigest;changed2.policyDigest=stableDigest(body);assert.throws(()=>validateAdmissionPolicy(changed2),/sourceSha must equal debugCommit/);});

test('calibration admission v2 explicitly carries no repository-governance authority',()=>{const q=qualificationFor(corpus),r=liveRecordFor(corpus),a=evaluateAdmission({policy,reviewedCorpus:corpus,qualification:q,modelRecord:r,expectedDebugCommit:r.debugCommit,expectedCoreCommit:r.coreCommit});assert.equal(a.schemaVersion,ADMISSION_VERSION);assert.equal(a.governanceLockDigest,null);assert.equal(a.governanceReceiptDigest,null);assert.equal(a.ready,false);assert.ok(a.gaps.includes('promotion admission policy is not reviewed'));assert.ok(a.gaps.includes('token efficiency is not calibrated'));assert.match(a.digest,/^[0-9a-f]{64}$/);});

test('promotion admission requires and binds same-run reviewed repository governance',()=>{
  const reviewed=clone(corpus);reviewed.promotionEligible=true;const q=qualificationFor(reviewed),r=liveRecordFor(reviewed,{promotionEligible:true}),p=reviewedPolicy(reviewed),g=governanceFor();
  assert.throws(()=>evaluateAdmission({policy:p,reviewedCorpus:reviewed,qualification:q,modelRecord:r,requirePromotionEligible:true}),/requires reviewed repository governance evidence/);
  const a=evaluateAdmission({policy:p,reviewedCorpus:reviewed,qualification:q,modelRecord:r,...g,expectedDebugCommit:r.debugCommit,expectedCoreCommit:r.coreCommit,requirePromotionEligible:true});
  assert.equal(a.ready,true);assert.deepEqual(a.gaps,[]);assert.equal(a.governanceLockDigest,g.governanceLock.lockDigest);assert.equal(a.governanceReceiptDigest,g.governanceReceipt.digest);assert.equal(a.requirePromotionEligible,true);
});

test('promotion admission refuses governance assembled from a different workflow run',()=>{
  const reviewed=clone(corpus);reviewed.promotionEligible=true;
  const q=qualificationFor(reviewed),r=liveRecordFor(reviewed,{promotionEligible:true}),p=reviewedPolicy(reviewed),g=governanceFor({runId:'99'});
  assert.throws(()=>evaluateAdmission({policy:p,reviewedCorpus:reviewed,qualification:q,modelRecord:r,...g,requirePromotionEligible:true}),/governance\/model runContext mismatch: runId/);
});

test('reviewed policy is invalid for a different Safe Core or reviewed corpus than its calibration evidence',()=>{const reviewed=clone(corpus);reviewed.promotionEligible=true;const q=qualificationFor(reviewed),r=liveRecordFor(reviewed,{promotionEligible:true}),g=governanceFor();const coreMismatch=reviewedPolicy(reviewed,{coreCommit:'9'.repeat(40)});assert.throws(()=>evaluateAdmission({policy:coreMismatch,reviewedCorpus:reviewed,qualification:q,modelRecord:r,...g}),/calibration Safe Core does not match/);const corpusMismatch=reviewedPolicy(reviewed);corpusMismatch.calibrationEvidence.corpusDigest='2'.repeat(64);const body={...corpusMismatch};delete body.policyDigest;corpusMismatch.policyDigest=stableDigest(body);assert.throws(()=>evaluateAdmission({policy:corpusMismatch,reviewedCorpus:reviewed,qualification:q,modelRecord:r,...g}),/calibration corpus does not match/);});

test('admission refuses qualification/model evidence assembled from different workflow runs',()=>{const q=qualificationFor(corpus,{runId:'41'}),r=liveRecordFor(corpus,{runId:'42'});assert.throws(()=>evaluateAdmission({policy,reviewedCorpus:corpus,qualification:q,modelRecord:r}),/runContext mismatch: runId/);});

test('admission safety gates remain zero-tolerance even with a reviewed calibrated policy',()=>{const reviewed=clone(corpus);reviewed.promotionEligible=true;const q=qualificationFor(reviewed),base=liveRecordFor(reviewed,{promotionEligible:true}),p=reviewedPolicy(reviewed),g=governanceFor(),changed=clone(base),insufficient=toEvaluationCorpus(reviewed).cases.find(x=>x.expected.assessment==='insufficient'),item=changed.cases.find(x=>x.caseId===insufficient.id);item.judgment.causalAssessment='supported';item.judgment.patchProposed=true;item.judgment.patchDisposition='accept';delete changed.recordDigest;changed.recordDigest=stableDigest(changed);const a=evaluateAdmission({policy:p,reviewedCorpus:reviewed,qualification:q,modelRecord:changed,...g,requirePromotionEligible:true});assert.equal(a.ready,false);assert.ok(a.gaps.some(x=>x.startsWith('falseSupport ')));assert.ok(a.gaps.some(x=>x.startsWith('falseFixCandidates ')));assert.ok(a.gaps.some(x=>x.startsWith('patchPolicyViolations ')));});

test('promotion model workflow binds governance into admission before independent receipt revalidation',()=>{const workflow=fs.readFileSync(path.join(__dirname,'..','.github','workflows','promotion-model-eval.yml'),'utf8'),governanceIndex=workflow.indexOf('Verify repository governance for promotion'),qualificationIndex=workflow.indexOf('Qualify historical transitions for this exact evaluation run'),modelIndex=workflow.indexOf('Record historical live-model evaluation'),admissionIndex=workflow.indexOf('Bind qualification, live metrics, governance, and promotion admission policy'),revalidateIndex=workflow.indexOf('Re-validate promotion admission receipt');assert.ok(governanceIndex>0&&qualificationIndex>governanceIndex&&modelIndex>qualificationIndex&&admissionIndex>modelIndex&&revalidateIndex>admissionIndex);assert.match(workflow,/promotion-admission\.js[\s\S]{0,800}--governance-lock PROMOTION_REPOSITORY_GOVERNANCE_LOCK\.json[\s\S]{0,200}--governance PROMOTION_REPOSITORY_GOVERNANCE\.json/);assert.match(workflow,/validate-promotion-admission\.js/);assert.match(workflow,/--require-promotion-eligible/);assert.match(workflow,/permissions:\s*\n\s+contents:\s*read\b/);assert.doesNotMatch(workflow,/\bcontents:\s*write\b/i);assert.doesNotMatch(workflow,/\bid-token:\s*write\b/i);assert.doesNotMatch(workflow,/\bgit\s+push\b/i);});
