'use strict';
const vscode=require('vscode');
const {runDebugSession,resumeDebugSession}=require('./src/debug');
const {gitApply}=require('./src/patch');
const {runExplicitCommand}=require('./src/runner');
const {inspectRuntimeFromOptions}=require('./src/codex');
const {collectGitContext}=require('./src/git-context');
const {listSessions,readSession}=require('./src/session-store');
let output,lastResult;
function workspace(){const folder=vscode.workspace.workspaceFolders?.[0];if(!folder)throw new Error('Open a workspace first.');if(!vscode.workspace.isTrusted)throw new Error('Codex Debug Safe is disabled in untrusted workspaces.');return folder.uri.fsPath;}
function sessionRoot(){const ws=workspace(),git=collectGitContext(ws,{includeHistory:false});return git.root||ws;}
function config(){const c=vscode.workspace.getConfiguration('safeCodexDebug');return {workspace:workspace(),codexPath:c.get('codexPath','codex'),model:c.get('model',''),verifierModel:c.get('verifierModel',''),modelSelectionStrategy:c.get('modelSelectionStrategy','auto'),modelCandidates:c.get('modelCandidates',[]),modelCompatibilityPolicy:c.get('modelCompatibilityPolicy','strict'),providerMode:c.get('providerMode','auto'),providerBaseUrl:c.get('providerBaseUrl',''),providerApiKeyEnv:c.get('providerApiKeyEnv','OPENAI_API_KEY'),providerCredentialSource:c.get('providerCredentialSource','auto'),providerAllowInsecureHttp:c.get('providerAllowInsecureHttp',false),maxEstimatedTokens:c.get('maxEstimatedTokens',80000),commandTimeoutMs:c.get('commandTimeoutSeconds',300)*1000,maxLogBytes:c.get('maxLogBytes',8388608),includeGitHistory:c.get('includeGitHistory',true)};}
async function run(opts){output.show(true);output.appendLine('Codex Debug Safe: collecting bounded evidence and running two-pass causal analysis...');lastResult=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Codex Debug Safe',cancellable:false},()=>runDebugSession({...config(),...opts}));output.appendLine(lastResult.markdown);vscode.window.showInformationMessage(`Codex Debug Safe: ${lastResult.fixStatus} (${Math.round(lastResult.investigation.confidence*100)}%)`);return lastResult;}
async function resume(sessionId,verifyCommand){output.show(true);lastResult=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Codex Debug Safe: verifying stored failure',cancellable:false},()=>resumeDebugSession({...config(),resume:sessionId,verifyCommand,verifyRuns:3}));output.appendLine(lastResult.markdown);const fn=lastResult.fixStatus==='verified'?vscode.window.showInformationMessage:vscode.window.showWarningMessage;fn(`Codex Debug Safe resumed: ${lastResult.fixStatus}`);return lastResult;}
async function chooseSession(){const root=sessionRoot(),items=listSessions(root).map(x=>({label:x.sessionId,description:new Date(x.mtimeMs).toLocaleString()}));if(!items.length){vscode.window.showWarningMessage('No persisted Codex Debug Safe sessions found.');return null;}return vscode.window.showQuickPick(items,{title:'Codex Debug Safe sessions',placeHolder:'Choose a persisted evidence-bound session'});}
async function activate(context){output=vscode.window.createOutputChannel('Codex Debug Safe');context.subscriptions.push(output,
vscode.commands.registerCommand('safeCodexDebug.debugSelection',async()=>{const editor=vscode.window.activeTextEditor;if(!editor||editor.selection.isEmpty)return vscode.window.showWarningMessage('Select failure/log evidence first.');return run({text:editor.document.getText(editor.selection),sourceType:'selection',sourceLabel:editor.document.fileName});}),
vscode.commands.registerCommand('safeCodexDebug.debugLogFile',async()=>{const files=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Debug failure log'});if(files?.[0])return run({logFile:files[0].fsPath});}),
vscode.commands.registerCommand('safeCodexDebug.debugCore',async()=>{const core=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select core dump'});if(!core?.[0])return;const exe=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select matching executable'});if(exe?.[0])return run({coreFile:core[0].fsPath,executable:exe[0].fsPath});}),
vscode.commands.registerCommand('safeCodexDebug.debugCommand',async()=>{const command=await vscode.window.showInputBox({title:'Explicit reproduction command',prompt:'This exact command will execute in the workspace. Model output cannot populate it.',ignoreFocusOut:true});if(command)return run({command,reproRuns:3});}),
vscode.commands.registerCommand('safeCodexDebug.safeBisect',async()=>{const command=await vscode.window.showInputBox({title:'Safe Bisect reproduction command',prompt:'Exact command to execute against historical commits in an isolated clone.',ignoreFocusOut:true});if(!command)return;const good=await vscode.window.showInputBox({title:'Known-good Git ref',prompt:'Commit/tag/ref that is known to pass the reproduction.',ignoreFocusOut:true});if(!good)return;const choice=await vscode.window.showWarningMessage('Safe Bisect will execute your exact command against historical repository code inside an isolated temporary clone. Historical code may be untrusted. Continue?',{modal:true},'Run Safe Bisect');if(choice!=='Run Safe Bisect')return;return run({command,reproRuns:2,bisectGood:good,allowHistoricalExecution:true});}),
vscode.commands.registerCommand('safeCodexDebug.applyLastPatch',async()=>{if(!lastResult?.investigation?.patch?.unifiedDiff)return vscode.window.showWarningMessage('No causal-verifier-accepted patch is available.');const choice=await vscode.window.showWarningMessage(`Apply verifier-accepted patch (${lastResult.investigation.patch.risk} risk) after git apply --check?`,'Apply');if(choice!=='Apply')return;const applied=gitApply(lastResult.investigation.patch.unifiedDiff,{cwd:lastResult.gitContext.root||workspace(),apply:true});output.appendLine(`Patch applied to: ${applied.paths.join(', ')}`);vscode.window.showInformationMessage('Patch applied but not committed. Use Verify Last Fix to bind post-change execution to the stored failing baseline.');}),
vscode.commands.registerCommand('safeCodexDebug.verifyLastFix',async()=>{const command=await vscode.window.showInputBox({title:'Explicit verification command',prompt:'This exact command will execute. A verified verdict additionally requires a bound failing baseline and observed workspace mutation.',ignoreFocusOut:true});if(!command)return;if(lastResult?.evidence?.reproduction?.failures&&lastResult?.sessionId){try{return await resume(lastResult.sessionId,command);}catch(error){output.appendLine(`Bound verification unavailable: ${error.message}`);}}const result=runExplicitCommand(command,{cwd:workspace(),timeoutMs:config().commandTimeoutMs,maxBuffer:config().maxLogBytes});output.appendLine(`Standalone verification exit=${result.exitCode} timeout=${result.timedOut} duration=${result.durationMs}ms (unbound)`);result.exitCode===0?vscode.window.showInformationMessage('Command passed, but it is unbound and does not prove a prior fix.'):vscode.window.showErrorMessage(`Verification command failed with exit ${result.exitCode}.`);}),
vscode.commands.registerCommand('safeCodexDebug.resumeSession',async()=>{const picked=await chooseSession();if(!picked)return;const command=await vscode.window.showInputBox({title:`Resume ${picked.label}`,prompt:'Explicit post-change verification command',ignoreFocusOut:true});if(command)return resume(picked.label,command);}),
vscode.commands.registerCommand('safeCodexDebug.showSessions',async()=>{const picked=await chooseSession();if(!picked)return;const session=readSession(sessionRoot(),picked.label);output.show(true);output.appendLine(session.markdown||JSON.stringify(session,null,2));}),
vscode.commands.registerCommand('safeCodexDebug.checkEnvironment',async()=>{try{const r=inspectRuntimeFromOptions(config());output.appendLine(`Runtime source=${r.source} provider=${r.providerId||r.runtime?.provider?.mode||'unknown'}`);vscode.window.showInformationMessage(`Codex Debug Safe runtime: ${r.source}`);}catch(error){vscode.window.showErrorMessage(`Codex Debug Safe environment failed: ${error.message}`);}}),
vscode.commands.registerCommand('safeCodexDebug.showOutput',()=>output.show(true)));
}
function deactivate(){}
module.exports={activate,deactivate};
