'use strict';
const vscode=require('vscode');
const {runDebugSession}=require('./src/debug');
const {gitApply}=require('./src/patch');
const {runExplicitCommand}=require('./src/runner');
const {inspectRuntimeFromOptions}=require('./src/codex');
let output,lastResult;
function workspace(){const folder=vscode.workspace.workspaceFolders?.[0];if(!folder)throw new Error('Open a workspace first.');if(!vscode.workspace.isTrusted)throw new Error('Codex Debug Safe is disabled in untrusted workspaces.');return folder.uri.fsPath;}
function config(){const c=vscode.workspace.getConfiguration('safeCodexDebug');return {workspace:workspace(),codexPath:c.get('codexPath','codex'),model:c.get('model',''),modelSelectionStrategy:c.get('modelSelectionStrategy','auto'),modelCandidates:c.get('modelCandidates',[]),modelCompatibilityPolicy:c.get('modelCompatibilityPolicy','strict'),providerMode:c.get('providerMode','auto'),providerBaseUrl:c.get('providerBaseUrl',''),providerApiKeyEnv:c.get('providerApiKeyEnv','OPENAI_API_KEY'),providerCredentialSource:c.get('providerCredentialSource','auto'),providerAllowInsecureHttp:c.get('providerAllowInsecureHttp',false),maxEstimatedTokens:c.get('maxEstimatedTokens',80000),commandTimeoutMs:c.get('commandTimeoutSeconds',300)*1000,maxLogBytes:c.get('maxLogBytes',8388608),includeGitHistory:c.get('includeGitHistory',true)};}
async function run(opts){output.show(true);output.appendLine('Codex Debug Safe: collecting bounded evidence...');lastResult=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Codex Debug Safe',cancellable:false},()=>runDebugSession({...config(),...opts}));output.appendLine(lastResult.markdown);vscode.window.showInformationMessage(`Codex Debug Safe: ${lastResult.fixStatus} (${Math.round(lastResult.investigation.confidence*100)}%)`);return lastResult;}
async function activate(context){output=vscode.window.createOutputChannel('Codex Debug Safe');context.subscriptions.push(output,
 vscode.commands.registerCommand('safeCodexDebug.debugSelection',async()=>{const editor=vscode.window.activeTextEditor;if(!editor||editor.selection.isEmpty)return vscode.window.showWarningMessage('Select failure/log evidence first.');return run({text:editor.document.getText(editor.selection),sourceType:'selection',sourceLabel:editor.document.fileName});}),
 vscode.commands.registerCommand('safeCodexDebug.debugLogFile',async()=>{const files=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Debug failure log'});if(files?.[0])return run({logFile:files[0].fsPath});}),
 vscode.commands.registerCommand('safeCodexDebug.debugCommand',async()=>{const command=await vscode.window.showInputBox({title:'Explicit reproduction command',prompt:'This exact command will execute in the workspace. Model output cannot populate it.',ignoreFocusOut:true});if(command)return run({command});}),
 vscode.commands.registerCommand('safeCodexDebug.applyLastPatch',async()=>{if(!lastResult?.investigation?.patch?.unifiedDiff)return vscode.window.showWarningMessage('No proposed patch is available.');const choice=await vscode.window.showWarningMessage(`Apply model-proposed patch (${lastResult.investigation.patch.risk} risk) after git apply --check?`,'Apply');if(choice!=='Apply')return;const applied=gitApply(lastResult.investigation.patch.unifiedDiff,{cwd:lastResult.gitContext.root||workspace(),apply:true});output.appendLine(`Patch applied to: ${applied.paths.join(', ')}`);vscode.window.showInformationMessage('Patch applied. It is not verified or committed. Run Verify Last Fix.');}),
 vscode.commands.registerCommand('safeCodexDebug.verifyLastFix',async()=>{const command=await vscode.window.showInputBox({title:'Explicit verification command',prompt:'This command will execute in the workspace.',ignoreFocusOut:true});if(!command)return;const result=runExplicitCommand(command,{cwd:workspace(),timeoutMs:config().commandTimeoutMs,maxBuffer:config().maxLogBytes});output.appendLine(`Verification exit=${result.exitCode} timeout=${result.timedOut} duration=${result.durationMs}ms`);result.exitCode===0?vscode.window.showInformationMessage('Verification command passed.'):vscode.window.showErrorMessage(`Verification command failed with exit ${result.exitCode}.`);}),
 vscode.commands.registerCommand('safeCodexDebug.checkEnvironment',async()=>{try{const r=inspectRuntimeFromOptions(config());output.appendLine(`Runtime source=${r.source} provider=${r.providerId||r.runtime?.provider?.mode||'unknown'}`);vscode.window.showInformationMessage(`Codex Debug Safe runtime: ${r.source}`);}catch(error){vscode.window.showErrorMessage(`Codex Debug Safe environment failed: ${error.message}`);}}),
 vscode.commands.registerCommand('safeCodexDebug.showOutput',()=>output.show(true)));
}
function deactivate(){}
module.exports={activate,deactivate};
