'use strict';
const vscode=require('vscode');
const {runDebugSession,resumeDebugSession,applyDebugSessionPatch,rollbackDebugSession}=require('./src/debug');
const {runExplicitCommand}=require('./src/runner');
const {inspectRuntimeFromOptions}=require('./src/codex');
const {collectGitContext}=require('./src/git-context');
const {listSessions,readSession}=require('./src/session-store');
let output,lastResult;
function workspace(){const folder=vscode.workspace.workspaceFolders?.[0];if(!folder)throw new Error('Open a workspace first.');if(!vscode.workspace.isTrusted)throw new Error('Codex Debug Safe is disabled in untrusted workspaces.');return folder.uri.fsPath;}
function sessionRoot(){const ws=workspace(),git=collectGitContext(ws,{includeHistory:false});return git.root||ws;}
function config(){const c=vscode.workspace.getConfiguration('safeCodexDebug');return {workspace:workspace(),codexPath:c.get('codexPath','codex'),model:c.get('model',''),verifierModel:c.get('verifierModel',''),modelSelectionStrategy:c.get('modelSelectionStrategy','auto'),modelCandidates:c.get('modelCandidates',[]),modelCompatibilityPolicy:c.get('modelCompatibilityPolicy','strict'),providerMode:c.get('providerMode','auto'),providerBaseUrl:c.get('providerBaseUrl',''),providerApiKeyEnv:c.get('providerApiKeyEnv','OPENAI_API_KEY'),providerCredentialSource:c.get('providerCredentialSource','auto'),providerAllowInsecureHttp:c.get('providerAllowInsecureHttp',false),maxEstimatedTokens:c.get('maxEstimatedTokens',80000),commandTimeoutMs:c.get('commandTimeoutSeconds',300)*1000,maxLogBytes:c.get('maxLogBytes',8388608),includeGitHistory:c.get('includeGitHistory',true)};}
async function run(opts){output.show(true);output.appendLine('Codex Debug Safe: collecting bounded evidence and running two-pass causal analysis...');lastResult=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Codex Debug Safe',cancellable:false},()=>runDebugSession({...config(),...opts}));output.appendLine(lastResult.markdown);vscode.window.showInformationMessage(`Codex Debug Safe: ${lastResult.fixStatus} (${Math.round(lastResult.investigation.confidence*100)}%)`);return lastResult;}
async function resume(sessionId,verifyCommand){output.show(true);lastResult=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Codex Debug Safe: verifying stored failure',cancellable:false},()=>resumeDebugSession({...config(),resume:sessionId,verifyCommand,verifyRuns:3}));output.appendLine(lastResult.markdown);const fn=lastResult.fixStatus==='verified'?vscode.window.showInformationMessage:vscode.window.showWarningMessage;fn(`Codex Debug Safe resumed: ${lastResult.fixStatus}`);return lastResult;}
async function chooseSession(title='Codex Debug Safe sessions'){const root=sessionRoot(),items=listSessions(root).map(x=>({label:x.sessionId,description:new Date(x.mtimeMs).toLocaleString()}));if(!items.length){vscode.window.showWarningMessage('No persisted Codex Debug Safe sessions found.');return null;}return vscode.window.showQuickPick(items,{title,placeHolder:'Choose a persisted evidence-bound session'});}
async function applyStoredSession(sessionId){lastResult=await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:'Codex Debug Safe: applying checked patch',cancellable:false},()=>applyDebugSessionPatch({...config(),sessionId}));output.show(true);output.appendLine(lastResult.markdown);vscode.window.showInformationMessage(`Patch applied with rollback snapshot ${lastResult.patch?.snapshotId||'unknown'}. It is not committed or verified.`);return lastResult;}
async function rollbackStoredSession(sessionId){const result=rollbackDebugSession({...config(),sessionId});output.show(true);output.appendLine(`Rolled back snapshot ${result.snapshotId}: ${result.paths.join(', ')}`);lastResult=null;vscode.window.showInformationMessage(`Codex Debug Safe rollback completed for ${result.paths.length} path(s).`);return result;}
async function embeddedFaultOptions(){const log=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select HardFault/fault log'});if(!log?.[0])return null;const mode=await vscode.window.showQuickPick([{label:'Linker map',value:'map',description:'Deterministic nearest symbol + offset; no external symbolizer required.'},{label:'ELF',value:'elf',description:'Fixed-argv addr2line using controller-extracted PC/LR only.'},{label:'Map + ELF',value:'both',description:'Use deterministic map and fixed-argv ELF symbolization together.'}],{title:'Embedded symbol evidence',placeHolder:'Choose bounded symbol sources'});if(!mode)return null;const opts={logFile:log[0].fsPath,kind:'mcu'};if(mode.value==='map'||mode.value==='both'){const map=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select linker map'});if(!map?.[0])return null;opts.mapFile=map[0].fsPath;}if(mode.value==='elf'||mode.value==='both'){const elf=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select firmware ELF'});if(!elf?.[0])return null;opts.elfFile=elf[0].fsPath;opts.addr2line='auto';const mapping=await vscode.window.showInputBox({title:'Optional embedded source-prefix map',prompt:'If DWARF points at an external build root, enter ABSOLUTE_OLD_PREFIX=WORKSPACE_TARGET (for example /build/fw=.). Leave empty to keep external paths redacted.',placeHolder:'/build/fw=.',ignoreFocusOut:true});if(mapping?.trim())opts.sourcePrefixMaps=[mapping.trim()];}return opts;}
async function activate(context){output=vscode.window.createOutputChannel('Codex Debug Safe');context.subscriptions.push(output,
vscode.commands.registerCommand('safeCodexDebug.debugSelection',async()=>{const editor=vscode.window.activeTextEditor;if(!editor||editor.selection.isEmpty)return vscode.window.showWarningMessage('Select failure/log evidence first.');return run({text:editor.document.getText(editor.selection),sourceType:'selection',sourceLabel:editor.document.fileName});}),
vscode.commands.registerCommand('safeCodexDebug.debugLogFile',async()=>{const files=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Debug failure log'});if(files?.[0])return run({logFile:files[0].fsPath});}),
vscode.commands.registerCommand('safeCodexDebug.debugCore',async()=>{const core=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select core dump'});if(!core?.[0])return;const exe=await vscode.window.showOpenDialog({canSelectMany:false,openLabel:'Select matching executable'});if(exe?.[0])return run({coreFile:core[0].fsPath,executable:exe[0].fsPath});}),
vscode.commands.registerCommand('safeCodexDebug.debugEmbeddedFault',async()=>{const opts=await embeddedFaultOptions();if(opts)return run(opts);}),
vscode.commands.registerCommand('safeCodexDebug.debugCommand',async()=>{const command=await vscode.window.showInputBox({title:'Explicit reproduction command',prompt:'This exact command will execute in the workspace. Model output cannot populate it.',ignoreFocusOut:true});if(command)return run({command,reproRuns:3});}),
vscode.commands.registerCommand('safeCodexDebug.safeBisect',async()=>{const command=await vscode.window.showInputBox({title:'Safe Bisect reproduction command',prompt:'Exact command to execute against historical commits in an isolated clone.',ignoreFocusOut:true});if(!command)return;const good=await vscode.window.showInputBox({title:'Known-good Git ref',prompt:'Commit/tag/ref that is known to pass the reproduction.',ignoreFocusOut:true});if(!good)return;const choice=await vscode.window.showWarningMessage('Safe Bisect will execute your exact command against historical repository code inside fresh isolated temporary clones. Historical code may be untrusted. Continue?',{modal:true},'Run Safe Bisect');if(choice!=='Run Safe Bisect')return;return run({command,reproRuns:2,bisectGood:good,allowHistoricalExecution:true});}),
vscode.commands.registerCommand('safeCodexDebug.applyLastPatch',async()=>{let sessionId=lastResult?.sessionId;if(!sessionId){const picked=await chooseSession('Apply persisted Debug patch');if(!picked)return;sessionId=picked.label;}const stored=readSession(sessionRoot(),sessionId);if(!stored?.investigation?.patch?.unifiedDiff)return vscode.window.showWarningMessage('Selected session has no causal-verifier-accepted patch.');const choice=await vscode.window.showWarningMessage(`Apply verifier-accepted patch (${stored.investigation.patch.risk} risk) after workspace freshness, causal re-authorization, git apply --check, and rollback-snapshot gates?`,{modal:true},'Apply');if(choice!=='Apply')return;return applyStoredSession(sessionId);}),
vscode.commands.registerCommand('safeCodexDebug.rollbackLastPatch',async()=>{let sessionId=lastResult?.patch?.snapshotId?lastResult.sessionId:null;if(!sessionId){const picked=await chooseSession('Rollback applied Debug patch');if(!picked)return;sessionId=picked.label;}const stored=readSession(sessionRoot(),sessionId);if(!stored?.patch?.snapshotId)return vscode.window.showWarningMessage('Selected session has no rollback snapshot.');const choice=await vscode.window.showWarningMessage('Rollback restores only the recorded patch paths and will refuse if any of them changed after patch application. Continue?',{modal:true},'Rollback');if(choice!=='Rollback')return;try{return rollbackStoredSession(sessionId);}catch(error){vscode.window.showErrorMessage(`Rollback refused: ${error.message}`);}}),
vscode.commands.registerCommand('safeCodexDebug.verifyLastFix',async()=>{const command=await vscode.window.showInputBox({title:'Explicit verification command',prompt:'This exact command will execute. A verified verdict additionally requires a bound reproducible failing baseline and observed workspace mutation.',ignoreFocusOut:true});if(!command)return;if(lastResult?.evidence?.reproduction?.reproducibleFailure&&lastResult?.sessionId){try{return await resume(lastResult.sessionId,command);}catch(error){output.appendLine(`Bound verification unavailable: ${error.message}`);}}const result=runExplicitCommand(command,{cwd:workspace(),timeoutMs:config().commandTimeoutMs,maxBuffer:config().maxLogBytes});output.appendLine(`Standalone verification exit=${result.exitCode} timeout=${result.timedOut} duration=${result.durationMs}ms (unbound)`);result.exitCode===0?vscode.window.showInformationMessage('Command passed, but it is unbound and does not prove a prior fix.'):vscode.window.showErrorMessage(`Verification command failed with exit ${result.exitCode}.`);}),
vscode.commands.registerCommand('safeCodexDebug.resumeSession',async()=>{const picked=await chooseSession();if(!picked)return;const command=await vscode.window.showInputBox({title:`Resume ${picked.label}`,prompt:'Explicit post-change verification command',ignoreFocusOut:true});if(command)return resume(picked.label,command);}),
vscode.commands.registerCommand('safeCodexDebug.showSessions',async()=>{const picked=await chooseSession();if(!picked)return;const session=readSession(sessionRoot(),picked.label);output.show(true);output.appendLine(session.markdown||JSON.stringify(session,null,2));}),
vscode.commands.registerCommand('safeCodexDebug.checkEnvironment',async()=>{try{const r=inspectRuntimeFromOptions(config());output.appendLine(`Runtime source=${r.source} provider=${r.providerId||r.runtime?.provider?.mode||'unknown'}`);vscode.window.showInformationMessage(`Codex Debug Safe runtime: ${r.source}`);}catch(error){vscode.window.showErrorMessage(`Codex Debug Safe environment failed: ${error.message}`);}}),
vscode.commands.registerCommand('safeCodexDebug.showOutput',()=>output.show(true)));
}
function deactivate(){}
module.exports={activate,deactivate,embeddedFaultOptions};
