#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const contract=JSON.parse(read('product-contract.json'));
assert.equal(contract.lifecycle,'development','development baseline must remain lifecycle=development until explicit promotion');
assert.equal(contract.productVersion,'0.1.10','docs gate expects current development identity 0.1.10');
assert.equal(contract.promotionCorpusVersion,2,'docs gate expects Promotion Corpus v2');
assert.equal(contract.promotionAdmissionPolicyVersion,1,'docs gate expects Promotion Admission Policy v1');
const en=read('README.md'),zh=read('README.zh-CN.md'),arch=read('ARCHITECTURE.md'),security=read('SECURITY.md'),roadmap=read('ROADMAP.md'),modelEval=read('MODEL_EVALUATION.md'),projection=read('docs/INSUFFICIENT_EVIDENCE_PROJECTION.md'),admission=read('docs/PROMOTION_ADMISSION.md');
for(const flag of ['--core','--executable','--elf','--map','--addr2line','--bisect-good','--allow-historical-execution','--resume','--verify-command','--apply-session','--rollback-session','--kernel-system-map','--kernel-kaslr-slide','--kernel-module-symbol']){assert.ok(en.includes(flag),`README missing ${flag}`);assert.ok(zh.includes(flag),`README.zh-CN missing ${flag}`);}
for(const term of ['passed-unbound','development','verified fix does not by itself confirm a root-cause hypothesis','kaslr-unproven','EKASLRMISMATCH','module-build-id-required','module-build-id-mismatch','receipt-bound rollback child','EROLLBACKCONSUMED','EDEBUGROLLBACKBINDING'])assert.ok(en.toLowerCase().includes(term.toLowerCase()),`README missing ${term}`);
for(const term of ['development Family consumer','workspace freshness','Debug Receipt','append-only','Consumer CI Receipt','KASLR slide','kernel-module-buildid','rollback-receipt-lineage'])assert.ok(arch.toLowerCase().includes(term.toLowerCase()),`ARCHITECTURE missing ${term}`);
for(const term of ['Historical execution','not an OS sandbox','contents: read','Promotion provenance versus historical execution','Promotion Corpus Qualification'])assert.ok(security.toLowerCase().includes(term.toLowerCase()),`SECURITY missing ${term}`);
assert.match(security,/Promotion Provenance must\s+(?:\*\*)?not(?:\*\*)?:[\s\S]{0,900}receive model\/API credentials/i);
assert.match(security,/Actual bad-fails\/fixed-passes proof remains in the manual `Promotion Corpus Qualification` authority domain/i);
for(const term of ['modelEvaluationRecordVersion = 1','promotionCorpusVersion = 2','promotionTransitionVersion = 1','promotionAdmissionPolicyVersion = 1','12/12','4/3','5/4','model-evaluation views: `15`','structural readiness floor is fully satisfied','promotionEligible=false','Promotion Provenance intentionally sees **12 historical transitions, not 15 evaluation views**','Promotion Admission v1','reviewed=false','minimumAssessmentAccuracy=null','minimumRootCauseTop1Accuracy=null','tokenEfficiency.calibrated=false','maximumTokensPerCase=null','contents: read'])assert.ok(modelEval.toLowerCase().includes(term.toLowerCase()),`MODEL_EVALUATION missing ${term}`);
assert.match(modelEval,/(?:do|does)\s+(?:\*\*)?not(?:\*\*)?\s+inherit[^\n]{0,180}`OPENAI_API_KEY`/i);
assert.match(modelEval,/following statements are\s+(?:\*\*)?not(?:\*\*)?\s+allowed until corresponding artifacts exist/i);
for(const forbiddenClaim of ['promotion corpus is fully qualified by historical execution','live RCA precision meets a production target','live insufficient-evidence accuracy meets a production target','false-fix rate and patch applicability are production-proven','live token efficiency is calibrated at production scale','Promotion Admission is ready','ready to move from `development` to `active`'])assert.ok(modelEval.toLowerCase().includes(forbiddenClaim.toLowerCase()),`MODEL_EVALUATION missing forbidden claim: ${forbiddenClaim}`);
for(const term of ['Promotion Corpus v2','summary-only','patchPolicy=forbidden','raw stdout/stderr','Git history','ground-truth summary','ground-truth files','twelve unique reviewed transitions and three authentic insufficient variants','fifteen model-evaluation views','3/3','12/12','promotionEligible=false','does **not** prove live-model insufficient-evidence accuracy'])assert.ok(projection.toLowerCase().includes(term.toLowerCase()),`projection security doc missing ${term}`);
for(const term of ['Promotion Admission v1','same GitHub Actions run and source commit','PROMOTION_CORPUS_QUALIFICATION.json','PROMOTION_MODEL_EVAL.json','PROMOTION_ADMISSION.json','reviewed=false','maximumFalseSupport=0','maximumFalseFixCandidates=0','maximumPatchPolicyViolations=0','minimumInsufficientEvidenceAccuracy=1','minimumAssessmentAccuracy=null','minimumRootCauseTop1Accuracy=null','tokenEfficiency.calibrated=false','maximumTokensPerCase=null','promotion_mode=false','promotion_mode=true','contents: read'])assert.ok(admission.toLowerCase().includes(term.toLowerCase()),`PROMOTION_ADMISSION missing ${term}`);
for(const implemented of ['Promotion Admission Policy v1','same-run Qualification/Model binding','Promotion Model Evaluation sequencing','0.1.10','12/12','5/4'])assert.ok(roadmap.toLowerCase().includes(implemented.toLowerCase()),`ROADMAP missing ${implemented}`);
for(const pending of ['trigger and retain a credential-backed calibration run','choose evidence-based minimum thresholds','calibrate token usage','reviewed=true','promotionEligible=true','promotion_mode=true','development -> active'])assert.match(roadmap,new RegExp(`\\[ \\].*${pending.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`,'i'));
assert.match(roadmap,/\[x\].*package \/ package-lock \/ product-contract development identity.*0\.1\.10/i);
process.stdout.write(JSON.stringify({lifecycle:contract.lifecycle,version:contract.productVersion,status:'current',modelEvaluationV1:true,promotionCorpusV2:true,promotionAdmissionPolicyV1:true,promotionCorpusCases:12,promotionCorpusRepositories:4,promotionCorpusFailureKinds:5,promotionCorpusInsufficientCases:3,promotionEvaluationViews:15,structuralPromotionReady:true,promotionEligible:false,admissionPolicyReviewed:false,tokenEfficiencyCalibrated:false,livePromotionMetrics:false})+'\n');
