#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const contract=JSON.parse(read('product-contract.json'));
assert.equal(contract.lifecycle,'development','development baseline must remain lifecycle=development until explicit promotion');
assert.equal(contract.promotionCorpusVersion,2,'docs gate expects Promotion Corpus v2');
const en=read('README.md'),zh=read('README.zh-CN.md'),arch=read('ARCHITECTURE.md'),security=read('SECURITY.md'),roadmap=read('ROADMAP.md'),modelEval=read('MODEL_EVALUATION.md'),projection=read('docs/INSUFFICIENT_EVIDENCE_PROJECTION.md');
for(const flag of ['--core','--executable','--elf','--map','--addr2line','--bisect-good','--allow-historical-execution','--resume','--verify-command','--apply-session','--rollback-session','--kernel-system-map','--kernel-kaslr-slide','--kernel-module-symbol']){assert.ok(en.includes(flag),`README missing ${flag}`);assert.ok(zh.includes(flag),`README.zh-CN missing ${flag}`);}
for(const term of ['passed-unbound','first-parent','development','failure transition','patch snapshots','verified fix does not by itself confirm a root-cause hypothesis','arm-none-eabi-addr2line','kaslr-unproven','EKASLRMISMATCH','module-build-id-required','module-build-id-mismatch','receipt-bound rollback child','EROLLBACKCONSUMED','EDEBUGROLLBACKBINDING'])assert.ok(en.toLowerCase().includes(term.toLowerCase()),`README missing ${term}`);
for(const term of ['修复进入 `verified` 并不自动等于根因 hypothesis 被确认','rollback child','EROLLBACKCONSUMED','EDEBUGROLLBACKBINDING'])assert.ok(zh.includes(term),`README.zh-CN missing ${term}`);
for(const term of ['development Family consumer','first-parent','workspace freshness','Debug Receipt','append-only','fresh temporary clone','Development Consumer Evidence pipeline','Consumer CI Receipt','KASLR slide','kaslr-unproven','EKASLRMISMATCH','logged BuildId','kernel-module-buildid','Receipt-bound rollback operation','rollback-receipt-lineage','EROLLBACKCONSUMED'])assert.ok(arch.toLowerCase().includes(term.toLowerCase()),`ARCHITECTURE missing ${term}`);
for(const term of ['debuginfod','Historical execution','not an OS sandbox','successful unbound','hard-linked','append-only','credential-like environment variables','self-digest','Development Consumer Evidence','@vscode/vsce@3.9.2','contents: read','kaslr-unproven','EKASLRMISMATCH','module-build-id-required','module-build-id-mismatch','kernel-module-buildid','EDEBUGROLLBACKBINDING','EROLLBACKCONSUMED','rollback-receipt-lineage','Promotion provenance versus historical execution','Promotion Corpus Qualification'])assert.ok(security.toLowerCase().includes(term.toLowerCase()),`SECURITY missing ${term}`);
assert.match(security,/Promotion Provenance must\s+(?:\*\*)?not(?:\*\*)?:[\s\S]{0,900}receive model\/API credentials/i);
assert.match(security,/Actual bad-fails\/fixed-passes proof remains in the manual `Promotion Corpus Qualification` authority domain/i);
for(const term of ['Contract fixture','Historical corpus qualification','Live model evaluation','modelEvaluationRecordVersion = 1','promotionCorpusVersion = 2','promotionTransitionVersion = 1','direct-parent-fix','refs/pull/N/head','12 reviewed cases','3 distinct repositories','4 failure kinds','3 insufficient-evidence negatives','OPENAI_API_KEY','GitHub tokens','not an OS sandbox','Promotion Corpus Qualification','Promotion Model Evaluation','promotion_mode=true','contents: read','4 reviewed direct-parent historical transitions','4/12','3/3','4/4','0/3','Codex Diagnose','Continuous Promotion Provenance','Insufficient-evidence variants','summary-only','patchPolicy = forbidden','includeGitHistory=false','no raw stdout/stderr'])assert.ok(modelEval.toLowerCase().includes(term.toLowerCase()),`MODEL_EVALUATION missing ${term}`);
for(const term of ['Promotion Corpus v2','one digest-bound insufficient-evidence evaluation variant','summary-only','patchPolicy=forbidden','raw stdout/stderr','Git history','ground-truth summary','ground-truth files','current reviewed corpus remains at 4 unique transitions and 0 insufficient variants'])assert.ok(projection.toLowerCase().includes(term.toLowerCase()),`projection security doc missing ${term}`);
assert.match(modelEval,/do\s+(?:\*\*)?not(?:\*\*)?\s+inherit[^\n]{0,160}`OPENAI_API_KEY`/i);
assert.match(modelEval,/following statements are\s+(?:\*\*)?not(?:\*\*)?\s+allowed until corresponding artifacts exist/i);
for(const forbiddenClaim of ['the promotion corpus is ready','live RCA precision meets a production target','false-fix rate is production-proven across real repositories','live token efficiency is calibrated at production scale','ready to move from `development` to `active`'])assert.ok(modelEval.toLowerCase().includes(forbiddenClaim.toLowerCase()),`MODEL_EVALUATION missing forbidden promotion claim: ${forbiddenClaim}`);
for(const implemented of ['Safe Bisect','reproducible development VSIX gate','Consumer CI Receipt','executable fix-quality benchmark','Model Evaluation Record v1','4 unique reviewed direct-parent transitions','continuous read-only Promotion Provenance','Promotion Corpus v2 insufficient-evidence variant contract','0.1.5'])assert.ok(roadmap.toLowerCase().includes(implemented.toLowerCase()),`ROADMAP missing ${implemented}`);
assert.match(roadmap,/\[x\].*Promotion Corpus v2 insufficient-evidence variant contract/i);
assert.match(roadmap,/\[x\].*4 unique reviewed direct-parent transitions.*Codex Debug, Safe Core and Codex Diagnose/i);
assert.match(roadmap,/\[x\].*package \/ package-lock \/ product-contract development identity.*0\.1\.5/i);
for(const pending of ['8 more unique reviewed historical transitions','3 authentic insufficient-evidence variants','recorded live-model RCA corpus','live-model false-fix and patch-applicability benchmark across real repositories','live model token-usage calibration','explicit model behavioral canary where credentials are available'])assert.match(roadmap,new RegExp(`\\[ \\].*${pending.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`,'i'));
process.stdout.write(JSON.stringify({lifecycle:contract.lifecycle,status:'current',consumerEvidence:true,modelEvaluationV1:true,promotionCorpusV2:true,promotionProjectionV1:true,promotionCorpusCases:4,promotionCorpusRepositories:3,promotionCorpusFailureKinds:4,promotionCorpusInsufficientCases:0,livePromotionMetrics:false})+'\n');
