'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {compactFailureLog}=require('./codex-safe-core/diagnosis-platform');const {freeze,stableDigest}=require('./contracts');
const KINDS=Object.freeze(['text','sarif','junit','wav','perf','map','tombstone']);
function shaBuffer(buf){return crypto.createHash('sha256').update(buf).digest('hex');}
function specParts(spec){const text=String(spec||''),i=text.indexOf(':');if(i<=0)throw new Error('Artifact must be kind:path.');const kind=text.slice(0,i).toLowerCase(),file=text.slice(i+1);if(!KINDS.includes(kind)||!file)throw new Error(`Unsupported artifact: ${spec}`);return {kind,file};}
function boundedRead(file,maxBytes){const stat=fs.statSync(file);if(!stat.isFile())throw new Error('Artifact must be a regular file.');if(stat.size>maxBytes)throw new Error(`Artifact exceeds ${maxBytes} bytes: ${file}`);return fs.readFileSync(file);}
function parseSarif(buf){const json=JSON.parse(buf.toString('utf8')),rows=[];for(const run of json.runs||[])for(const r of run.results||[]){const loc=r.locations?.[0]?.physicalLocation,region=loc?.region||{};rows.push({ruleId:String(r.ruleId||''),level:String(r.level||''),message:String(r.message?.text||'').slice(0,500),file:String(loc?.artifactLocation?.uri||'').slice(0,512),line:Number(region.startLine||0)});if(rows.length>=80)break;}return {resultCount:rows.length,results:rows};}
function parseJUnit(buf){const text=buf.toString('utf8'),suite=(text.match(/<testsuite\b[^>]*>/i)||[])[0]||'',attr=name=>{const m=suite.match(new RegExp(`${name}=["']([^"']+)["']`,'i'));return m?m[1]:'';},failures=[];for(const m of text.matchAll(/<failure\b[^>]*?(?:message=["']([^"']*)["'])?[^>]*>([\s\S]*?)<\/failure>/gi)){failures.push(String(m[1]||m[2]||'failure').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,700));if(failures.length>=30)break;}return {tests:Number(attr('tests')||0),failures:Number(attr('failures')||0),errors:Number(attr('errors')||0),skipped:Number(attr('skipped')||0),time:Number(attr('time')||0),failureMessages:failures};}
function wavChunks(buf){if(buf.length<44||buf.toString('ascii',0,4)!=='RIFF'||buf.toString('ascii',8,12)!=='WAVE')throw new Error('Not a RIFF/WAVE file.');let off=12,fmt=null,data=null;while(off+8<=buf.length){const id=buf.toString('ascii',off,off+4),size=buf.readUInt32LE(off+4),start=off+8,end=Math.min(buf.length,start+size);if(id==='fmt ')fmt={format:buf.readUInt16LE(start),channels:buf.readUInt16LE(start+2),sampleRate:buf.readUInt32LE(start+4),byteRate:buf.readUInt32LE(start+8),blockAlign:buf.readUInt16LE(start+12),bitsPerSample:buf.readUInt16LE(start+14)};if(id==='data')data={start,size:end-start};off=end+(size%2);}if(!fmt||!data)throw new Error('WAV missing fmt/data chunk.');return {fmt,data};}
function parseWav(buf){const {fmt,data}=wavChunks(buf),bytesPerSample=Math.max(1,fmt.bitsPerSample/8),frameBytes=Math.max(1,fmt.blockAlign),frames=Math.floor(data.size/frameBytes),durationSec=fmt.sampleRate?frames/fmt.sampleRate:0;let peak=0,sumSq=0,sum=0,clips=0,count=0;const maxSamples=200000,stride=Math.max(1,Math.floor((frames*fmt.channels)/maxSamples));if(fmt.format===1&&fmt.bitsPerSample===16){let index=0;for(let off=data.start;off+1<data.start+data.size;off+=2,index++){if(index%stride)continue;const v=buf.readInt16LE(off)/32768;peak=Math.max(peak,Math.abs(v));sumSq+=v*v;sum+=v;if(Math.abs(v)>=0.999)clips++;count++;}}return {format:fmt.format,channels:fmt.channels,sampleRate:fmt.sampleRate,bitsPerSample:fmt.bitsPerSample,durationSec:Number(durationSec.toFixed(3)),peak:Number(peak.toFixed(6)),rms:count?Number(Math.sqrt(sumSq/count).toFixed(6)):null,dc:count?Number((sum/count).toFixed(6)):null,clipSampleRate:count?Number((clips/count).toFixed(6)):null,sampledValues:count,bytesPerSample};}
function parsePerf(buf){const json=JSON.parse(buf.toString('utf8')),events=Array.isArray(json)?json:(json.traceEvents||[]),rows=events.filter(e=>Number.isFinite(Number(e.dur))).map(e=>({name:String(e.name||'').slice(0,200),category:String(e.cat||'').slice(0,100),durationUs:Number(e.dur||0),pid:e.pid??null,tid:e.tid??null})).sort((a,b)=>b.durationUs-a.durationUs).slice(0,80);const byName={};for(const r of rows)byName[r.name]=(byName[r.name]||0)+r.durationUs;return {eventCount:events.length,topDurations:rows,topAggregate:Object.entries(byName).sort((a,b)=>b[1]-a[1]).slice(0,30).map(([name,durationUs])=>({name,durationUs}))};}
function parseText(buf){const c=compactFailureLog(buf.toString('utf8'),{maxBytes:48*1024,maxLines:300,contextLines:2});return {text:c.text,originalLines:c.originalLines,includedLines:c.includedLines,truncated:c.truncated};}
function loadArtifacts(specs,{workspace=process.cwd(),maxBytes=32*1024*1024}={}){const out=[];for(const spec of specs||[]){const {kind,file}=specParts(spec),absolute=path.resolve(workspace,file),buf=boundedRead(absolute,maxBytes);let summary;if(kind==='sarif')summary=parseSarif(buf);else if(kind==='junit')summary=parseJUnit(buf);else if(kind==='wav')summary=parseWav(buf);else if(kind==='perf')summary=parsePerf(buf);else summary=parseText(buf);out.push(freeze({kind,name:path.basename(absolute),digest:shaBuffer(buf),size:buf.length,summary,summaryDigest:stableDigest(summary)}));if(out.length>=12)break;}return freeze(out);}
module.exports={KINDS,specParts,parseSarif,parseJUnit,parseWav,parsePerf,parseText,loadArtifacts};
