'use strict';

const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const {freeze,stableDigest}=require('./contracts');
const {runReproductionSeries}=require('./reproduction');
const SECRET_ENV_KEY=/(?:^|_)(?:TOKEN|SECRET|PASSWORD|PASSWD|API[_-]?KEY|AUTH|CREDENTIALS?|PRIVATE[_-]?KEY|PAT)(?:_|$)|^(?:AWS_|AZURE_|GCP_|GOOGLE_APPLICATION_CREDENTIALS$|SSH_AUTH_SOCK$)/i;
function git(args,cwd,{allowFailure=false,maxBuffer=4*1024*1024,env=process.env}={}){try{return execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],maxBuffer,env}).trim();}catch(error){if(allowFailure)return '';throw Object.assign(new Error(`git ${args[0]} failed: ${String(error.stderr||error.message).trim().slice(0,500)}`),{code:'EBISECTGIT'});}}
function resolveCommit(root,ref){const sha=git(['rev-parse','--verify',`${String(ref)}^{commit}`],root,{allowFailure:true});if(!/^[0-9a-f]{40}$/.test(sha))throw Object.assign(new Error(`Invalid bisect commit/ref: ${ref}`),{code:'EBISECTREF'});return sha;}
function buildBisectPlan(root,{good,bad='HEAD',maxCommits=256}={}){if(!root)throw Object.assign(new Error('Safe bisect requires a Git repository.'),{code:'EBISECTREPO'});const goodSha=resolveCommit(root,good),badSha=resolveCommit(root,bad);try{execFileSync('git',['merge-base','--is-ancestor',goodSha,badSha],{cwd:root,stdio:'ignore'});}catch{throw Object.assign(new Error('Bisect good commit must be an ancestor of bad commit.'),{code:'EBISECTANCESTRY'});}const raw=git(['rev-list','--first-parent','--reverse',`${goodSha}..${badSha}`],root),commits=raw.split(/\r?\n/).filter(v=>/^[0-9a-f]{40}$/.test(v));if(!commits.length||commits[commits.length-1]!==badSha)throw Object.assign(new Error('Unable to construct a bounded first-parent path to bad commit.'),{code:'EBISECTPATH'});if(commits.length>maxCommits)throw Object.assign(new Error(`Bisect first-parent path exceeds ${maxCommits} commit bound.`),{code:'EBISECTLIMIT'});return freeze({strategy:'first-parent',good:goodSha,bad:badSha,commits,digest:stableDigest({strategy:'first-parent',good:goodSha,bad:badSha,commits})});}
function classifySeries(summary){if(!summary||!summary.runs)return 'unknown';if(summary.failures===0)return 'pass';if(summary.reproducibleFailure)return 'fail';return 'ambiguous';}
function safeHistoricalEnv(baseEnv,home){const env={};for(const [key,value] of Object.entries(baseEnv||{})){if(SECRET_ENV_KEY.test(key))continue;env[key]=value;}const safeHome=path.resolve(home);fs.mkdirSync(safeHome,{recursive:true,mode:0o700});const gitConfig=path.join(safeHome,'gitconfig');if(!fs.existsSync(gitConfig))fs.writeFileSync(gitConfig,'',{mode:0o600});env.HOME=safeHome;env.USERPROFILE=safeHome;env.XDG_CONFIG_HOME=path.join(safeHome,'.config');env.GIT_CONFIG_NOSYSTEM='1';env.GIT_CONFIG_GLOBAL=gitConfig;env.GIT_TERMINAL_PROMPT='0';env.GCM_INTERACTIVE='Never';delete env.SSH_AUTH_SOCK;return env;}
function runSafeBisect({root,good,bad='HEAD',command,runs=1,timeoutMs=300000,maxBuffer=8*1024*1024,allowHistoricalExecution=false,maxCommits=256}={}){if(!allowHistoricalExecution)throw Object.assign(new Error('Historical execution is disabled. Pass explicit authority before safe bisect.'),{code:'EBISECTAUTH'});if(!String(command||'').trim())throw Object.assign(new Error('Safe bisect requires an explicit reproduction command.'),{code:'EBISECTCOMMAND'});const plan=buildBisectPlan(root,{good,bad,maxCommits}),temp=fs.mkdtempSync(path.join(os.tmpdir(),'codex-debug-bisect-')),tested=[],safeEnv=safeHistoricalEnv(process.env,path.join(temp,'home'));try{const testCommit=sha=>{const candidate=path.join(temp,`candidate-${String(tested.length).padStart(3,'0')}-${sha.slice(0,12)}`);try{git(['clone','--quiet','--shared','--no-checkout',root,candidate],process.cwd(),{env:safeEnv});git(['checkout','--quiet','--detach','--force',sha],candidate,{env:safeEnv});git(['clean','-fdx'],candidate,{env:safeEnv});const series=runReproductionSeries(command,{runs,cwd:candidate,timeoutMs,maxBuffer,env:safeEnv}),classification=classifySeries(series.summary);tested.push({sha,classification,summary:series.summary});return classification;}finally{fs.rmSync(candidate,{recursive:true,force:true});}};const goodState=testCommit(plan.good);if(goodState!=='pass')return freeze({status:'blocked',reason:`good-endpoint-${goodState}`,plan,tested,firstBad:null,digest:stableDigest(tested)});const badState=testCommit(plan.bad);if(badState!=='fail')return freeze({status:'blocked',reason:`bad-endpoint-${badState}`,plan,tested,firstBad:null,digest:stableDigest(tested)});let lo=-1,hi=plan.commits.length-1;while(hi-lo>1){const mid=Math.floor((lo+hi)/2),sha=plan.commits[mid],state=testCommit(sha);if(state==='ambiguous'||state==='unknown')return freeze({status:'inconclusive',reason:`candidate-${state}`,plan,tested,firstBad:null,digest:stableDigest(tested)});if(state==='fail')hi=mid;else lo=mid;}const firstBad=plan.commits[hi];return freeze({status:'proven',reason:'bounded-first-parent-binary-search',plan,tested,firstBad,digest:stableDigest({plan:plan.digest,tested,firstBad})});}finally{fs.rmSync(temp,{recursive:true,force:true});}}
module.exports={SECRET_ENV_KEY,resolveCommit,buildBisectPlan,classifySeries,safeHistoricalEnv,runSafeBisect};
