'use strict';

const crypto=require('node:crypto');
const DEBUG_CONTRACT_VERSION=1,DEBUG_EVIDENCE_VERSION=1,DEBUG_RECEIPT_VERSION=1,HYPOTHESIS_LEDGER_VERSION=1;
const FAILURE_KINDS=Object.freeze(['build','test','crash','sanitizer','race','deadlock','oom','watchdog','kernel','android','mcu','audio','performance','dependency','infra','unknown']);
const HYPOTHESIS_STATUSES=Object.freeze(['open','supported','refuted','confirmed']),FIX_STATUSES=Object.freeze(['unresolved','diagnosed','proposed','applied-unverified','verified','regressed']);
function freeze(value){if(Array.isArray(value))return Object.freeze(value.map(freeze));if(value&&typeof value==='object')return Object.freeze(Object.fromEntries(Object.entries(value).map(([k,v])=>[k,freeze(v)])));return value;}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).filter(k=>value[k]!==undefined).sort().map(k=>[k,stable(value[k])]));return value;}
function stableDigest(value){return crypto.createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');}
function makeSessionId(evidenceDigest,createdAt=new Date().toISOString()){return `dbg-${stableDigest({evidenceDigest,createdAt}).slice(0,16)}`;}
function normalizeStrings(value,max=20,length=1000){return Object.freeze((Array.isArray(value)?value:[]).map(v=>String(v||'').trim().slice(0,length)).filter(Boolean).slice(0,max));}
function validateReceipt(value){if(!value||typeof value!=='object')throw Object.assign(new Error('Debug Receipt must be an object.'),{code:'EDEBUGRECEIPT'});if(value.schemaVersion!==DEBUG_RECEIPT_VERSION||value.kind!=='codex-debug')throw Object.assign(new Error('Unsupported Debug Receipt version/kind.'),{code:'EDEBUGRECEIPT'});for(const key of ['evidenceDigest','investigationDigest','debugFingerprint'])if(!/^[0-9a-f]{64}$/.test(String(value[key]||'')))throw Object.assign(new Error(`Invalid ${key}.`),{code:'EDEBUGRECEIPT'});if(!FIX_STATUSES.includes(value.fixStatus))throw Object.assign(new Error('Invalid fixStatus.'),{code:'EDEBUGRECEIPT'});if(!String(value.sessionId||'').startsWith('dbg-'))throw Object.assign(new Error('Invalid sessionId.'),{code:'EDEBUGRECEIPT'});return freeze(value);}
function createDebugReceipt({sessionId,evidence,investigation,ledger,verification,fixStatus,model='',codexVersion='',createdAt=new Date().toISOString()}={}){if(!evidence?.digest)throw new Error('Debug Receipt requires evidence.');const investigationDigest=stableDigest({rootCause:investigation?.rootCause||'',confidence:Number(investigation?.confidence||0),hypotheses:investigation?.hypotheses||[],patch:investigation?.patch||null,verificationPlan:investigation?.verificationPlan||[],causalVerification:investigation?.causalVerification||null});const subject={commitSha:String(evidence.git?.head||''),workspaceId:String(evidence.workspaceId||''),source:String(evidence.source?.label||'')};return validateReceipt({schemaVersion:DEBUG_RECEIPT_VERSION,kind:'codex-debug',sessionId:String(sessionId),subject,evidenceDigest:evidence.digest,investigationDigest,ledgerDigest:stableDigest(ledger||{}),verificationDigest:stableDigest(verification||{}),fixStatus:FIX_STATUSES.includes(fixStatus)?fixStatus:'unresolved',model:String(model||''),codexVersion:String(codexVersion||''),debugFingerprint:stableDigest({evidenceDigest:evidence.digest,investigationDigest,fixStatus}),createdAt:new Date(createdAt).toISOString()});}
module.exports=Object.freeze({DEBUG_CONTRACT_VERSION,DEBUG_EVIDENCE_VERSION,DEBUG_RECEIPT_VERSION,HYPOTHESIS_LEDGER_VERSION,FAILURE_KINDS,HYPOTHESIS_STATUSES,FIX_STATUSES,freeze,stableDigest,makeSessionId,normalizeStrings,createDebugReceipt,validateReceipt});
