'use strict';

const fs=require('node:fs'),path=require('node:path');
const {buildDebugEvidence,readBoundedFile}=require('./evidence');
const {collectGitContext}=require('./git-context');
const {createHypothesisLedger,confirmHypothesis}=require('./hypothesis-ledger');
const {runCodexInvestigation,runCodexCausalVerification,applyCausalVerification}=require('./codex');
const {runReproductionSeries}=require('./reproduction');
const {gitApply}=require('./patch');
const {symbolizeCore}=require('./symbolizer');
const {runSafeBisect}=require('./bisect');
const {makeSessionId,createDebugReceipt,freeze,stableDigest,validateStoredSession}=require('./contracts');
const {writeSession,readSession}=require('./session-store');
const {formatDebugReport}=require('./report');
function deterministicInvestigation(evidence){const signal=evidence.parsed?.signals?.[0]||`Deterministic classification: ${evidence.deterministic?.classification||'unknown'}`;return freeze({rootCause:`Deterministic-only mode cannot establish a causal root cause. Strongest observed signal: ${signal}`,confidence:Math.min(0.6,Number(evidence.deterministic?.confidence||0)),hypotheses:[{id:'H1',title:'Deterministic failure classification',claim:`Failure appears ${evidence.kind}/${evidence.deterministic?.classification||'unknown'}; model-backed causal analysis was disabled.`,status:'open',evidenceFor:[signal],evidenceAgainst:[],causalAnchors:[],verificationSteps:['Run model-backed investigation or supply a deterministic reproduction.']}],patch:null,verificationPlan:['Reproduce the failure with an explicit command before modifying code.'],coverageGaps:['Model-backed causal source reasoning was not performed in deterministic-only mode.'],causalVerification:null});}
function determineFixStatus({investigation,patchResult,verification}){if(verification?.status==='passed')return 'verified';if((patchResult?.applied||verification?.mutationObserved)&&verification?.status==='failed')return 'regressed';if(patchResult?.applied)return 'applied-unverified';if(investigation?.patch)return 'proposed';if(investigation?.causalVerification&&investigation.causalVerification.rootCauseAssessment!=='supported')return 'unresolved';if(investigation?.rootCause)return 'diagnosed';return 'unresolved';}
function verificationStatus(beforeSummary,afterSummary,mutationObserved){const baselineFailed=Boolean(beforeSummary&&beforeSummary.failures>0),baselineStrong=Boolean(beforeSummary&&(beforeSummary.runs===1?beforeSummary.failures===1:beforeSummary.failures>=2)&&beforeSummary.stableFailure!==false),postAllPass=Boolean(afterSummary&&afterSummary.runs>0&&afterSummary.failures===0);if(postAllPass&&baselineFailed&&baselineStrong&&mutationObserved)return 'passed';if(postAllPass)return 'passed-unbound';return 'failed';}
function confirmSupported(ledger,beforeSummary,afterSummary){const supported=ledger.entries.find(h=>h.status==='supported')||ledger.entries[0];return supported?confirmHypothesis(ledger,supported.id,{verificationEvidence:[`Observed ${beforeSummary.failures}/${beforeSummary.runs} failing baseline runs, an independently observed workspace-state mutation, and ${afterSummary.passes}/${afterSummary.runs} passing post-change runs.`]}):ledger;}
function writeOutputs(workspace,options,result){if(options.output)fs.writeFileSync(path.resolve(workspace,options.output),`${JSON.stringify(result,null,2)}\n`,'utf8');if(options.markdown)fs.writeFileSync(path.resolve(workspace,options.markdown),`${result.markdown}\n`,'utf8');}
async function runDebugSession(options={}){const workspace=path.resolve(options.workspace||process.cwd()),gitContext=collectGitContext(workspace,{includeHistory:options.includeGitHistory!==false});let before=null,beforeSummary=null,text='',source={type:'text',label:'inline'},symbolization=null,bisect=null;if(options.command){const series=runReproductionSeries(options.command,{runs:Number(options.reproRuns||1),cwd:workspace,timeoutMs:Number(options.commandTimeoutMs||300000),maxBuffer:Number(options.maxLogBytes||8*1024*1024)});before=series.representative;beforeSummary=series.summary;text=[`Reproduction series: runs=${series.summary.runs} failures=${series.summary.failures} passes=${series.summary.passes} stableFailure=${series.summary.stableFailure}`,before.stdout||'',before.stderr||''].join('\n');source={type:'command',label:'explicit reproduction command'};}else if(options.logFile){const absolute=path.resolve(workspace,options.logFile);text=readBoundedFile(absolute,Number(options.maxLogBytes||8*1024*1024));source={type:'file',label:absolute};}else{text=String(options.text||'');source={type:options.sourceType||'text',label:options.sourceLabel||'inline evidence'};}if(options.coreFile){symbolization=symbolizeCore({coreFile:path.resolve(workspace,options.coreFile),executable:path.resolve(workspace,options.executable),tool:options.debugger||'auto',cwd:workspace,timeoutMs:Number(options.commandTimeoutMs||120000),maxBytes:Math.min(Number(options.maxLogBytes||8*1024*1024),1024*1024)});text=[text,`--- FIXED-COMMAND ${symbolization.tool.toUpperCase()} CORE SYMBOLIZATION ---`,symbolization.text,'--- END CORE SYMBOLIZATION ---'].filter(Boolean).join('\n');source={type:source.type==='text'?'core':`${source.type}+core`,label:source.type==='text'?symbolization.core.name:source.label};}if(options.bisectGood){if(!gitContext.root)throw Object.assign(new Error('Safe bisect requires a Git workspace.'),{code:'EBISECTREPO'});bisect=runSafeBisect({root:gitContext.root,good:options.bisectGood,bad:options.bisectBad||gitContext.head,command:options.command,runs:Number(options.reproRuns||1),timeoutMs:Number(options.commandTimeoutMs||300000),maxBuffer:Number(options.maxLogBytes||8*1024*1024),allowHistoricalExecution:Boolean(options.allowHistoricalExecution)});}
const evidence=buildDebugEvidence({text,source,kind:options.kind||'auto',workspace,git:gitContext,commandResult:before,reproductionSummary:beforeSummary,artifactSpecs:options.artifacts||[],maxArtifactBytes:Number(options.maxArtifactBytes||32*1024*1024),symbolization,bisect}),sessionId=makeSessionId(evidence.digest);let modelResult=null,causalResult=null,investigation;if(options.deterministicOnly)investigation=deterministicInvestigation(evidence);else{modelResult=await runCodexInvestigation({evidence,gitContext,options});causalResult=await runCodexCausalVerification({evidence,gitContext,investigation:modelResult.investigation,options,model:modelResult.model});investigation=applyCausalVerification(modelResult.investigation,causalResult.verification);}let ledger=createHypothesisLedger(investigation.hypotheses,{evidenceDigest:evidence.digest}),patchResult=null;if(options.apply&&investigation.patch?.unifiedDiff){patchResult=gitApply(investigation.patch.unifiedDiff,{cwd:gitContext.root||workspace,apply:true});}else if(investigation.patch?.unifiedDiff){try{patchResult=gitApply(investigation.patch.unifiedDiff,{cwd:gitContext.root||workspace,apply:false});}catch(error){patchResult=freeze({checked:false,applied:false,error:error.message,paths:[]});}}
const postMutationContext=collectGitContext(workspace,{includeHistory:false}),mutationObserved=Boolean(gitContext.stateFingerprint&&postMutationContext.stateFingerprint&&gitContext.stateFingerprint!==postMutationContext.stateFingerprint);let verification={status:'not-run',baselineObserved:Boolean(beforeSummary),baselineSummary:beforeSummary,afterSummary:null,commandDigest:'',mutationObserved};const verifyCommand=String(options.verifyCommand||(patchResult?.applied?options.command:'')||'').trim();if(verifyCommand){const afterSeries=runReproductionSeries(verifyCommand,{runs:Number(options.verifyRuns||options.reproRuns||1),cwd:workspace,timeoutMs:Number(options.commandTimeoutMs||300000),maxBuffer:Number(options.maxLogBytes||8*1024*1024)}),status=verificationStatus(beforeSummary,afterSeries.summary,mutationObserved);verification={status,baselineObserved:Boolean(beforeSummary),baselineSummary:beforeSummary,afterSummary:afterSeries.summary,commandDigest:stableDigest(verifyCommand),mutationObserved};if(status==='passed')ledger=confirmSupported(ledger,beforeSummary,afterSeries.summary);}
const fixStatus=determineFixStatus({investigation,patchResult,verification}),receipt=createDebugReceipt({sessionId,evidence,investigation,ledger,verification,fixStatus,model:modelResult?.model||'deterministic-only',codexVersion:modelResult?.codexVersion||''}),result={sessionId,fixStatus,evidence,gitContext,investigation,ledger,patch:patchResult,verification,execution:modelResult?{hypothesis:{model:modelResult.model,codexVersion:modelResult.codexVersion,usage:modelResult.usage,durationMs:modelResult.durationMs,requestEstimate:modelResult.requestEstimate,runtimeSource:modelResult.runtimeSource,modelEvidence:modelResult.modelEvidence},causalVerification:causalResult?{model:causalResult.model,codexVersion:causalResult.codexVersion,usage:causalResult.usage,durationMs:causalResult.durationMs,requestEstimate:causalResult.requestEstimate}:null}:null,receipt};result.markdown=formatDebugReport(result);if(options.persist!==false)result.sessionPath=writeSession(gitContext.root||workspace,result);writeOutputs(workspace,options,result);return freeze(result);}
async function resumeDebugSession(options={}){const workspace=path.resolve(options.workspace||process.cwd()),current=collectGitContext(workspace,{includeHistory:options.includeGitHistory!==false}),root=current.root||workspace,previous=validateStoredSession(readSession(root,options.resume));if(previous.evidence?.git?.rootDigest&&current.root&&previous.evidence.git.rootDigest!==stableDigest(path.resolve(current.root)))throw Object.assign(new Error('Stored Debug session belongs to a different Git workspace.'),{code:'ESESSIONWORKSPACE'});const beforeSummary=previous.evidence?.reproduction;if(!beforeSummary?.failures)throw Object.assign(new Error('Stored session has no observed failing reproduction baseline; it cannot be resumed into verified state.'),{code:'ERESUMEBASELINE'});const mutationObserved=Boolean(previous.evidence?.git?.stateFingerprint&&current.stateFingerprint&&previous.evidence.git.stateFingerprint!==current.stateFingerprint),verifyCommand=String(options.verifyCommand||'').trim(),afterSeries=runReproductionSeries(verifyCommand,{runs:Number(options.verifyRuns||1),cwd:workspace,timeoutMs:Number(options.commandTimeoutMs||300000),maxBuffer:Number(options.maxLogBytes||8*1024*1024)}),status=verificationStatus(beforeSummary,afterSeries.summary,mutationObserved),verification={status,baselineObserved:true,baselineSummary:beforeSummary,afterSummary:afterSeries.summary,commandDigest:stableDigest(verifyCommand),mutationObserved,resumed:true};let ledger=previous.ledger;if(status==='passed')ledger=confirmSupported(ledger,beforeSummary,afterSeries.summary);const fixStatus=status==='passed'?'verified':mutationObserved?'regressed':previous.fixStatus,sessionId=makeSessionId(previous.evidence.digest),receipt=createDebugReceipt({sessionId,evidence:previous.evidence,investigation:previous.investigation,ledger,verification,fixStatus,model:previous.receipt?.model||'',codexVersion:previous.receipt?.codexVersion||''}),result={sessionId,fixStatus,evidence:previous.evidence,gitContext:current,investigation:previous.investigation,ledger,patch:previous.patch||null,verification,execution:null,lineage:{parentSessionId:previous.sessionId,parentDebugFingerprint:previous.receipt.debugFingerprint,resumedAt:new Date().toISOString()},receipt};result.markdown=formatDebugReport(result);if(options.persist!==false)result.sessionPath=writeSession(root,result);writeOutputs(workspace,options,result);return freeze(result);}
module.exports={deterministicInvestigation,determineFixStatus,verificationStatus,confirmSupported,runDebugSession,resumeDebugSession};
