'use strict';
const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');const {decodeCortexMFault}=require('./embedded');const {freeze,stableDigest}=require('./contracts');const ADDR2LINE_TOOLS=Object.freeze(['arm-none-eabi-addr2line','riscv64-unknown-elf-addr2line','riscv32-unknown-elf-addr2line','llvm-addr2line','addr2line']);
function boundedRegularFile(file,label,maxBytes){const absolute=path.resolve(String(file||''));if(!file)throw Object.assign(new Error(`${label} is required.`),{code:'EEMBEDSYMBOLINPUT'});const stat=fs.lstatSync(absolute);if(stat.isSymbolicLink()||!stat.isFile())throw Object.assign(new Error(`${label} must be a regular non-symlink file.`),{code:'EEMBEDSYMBOLINPUT'});if(stat.size>maxBytes)throw Object.assign(new Error(`${label} exceeds ${maxBytes} bytes.`),{code:'EEMBEDSYMBOLLIMIT'});return {absolute,size:stat.size,mtimeMs:Math.floor(stat.mtimeMs)};}
function codeAddresses(text){const fault=decodeCortexMFault(text),rows=[];for(const name of ['pc','lr']){const value=fault?.registers?.[name];if(Number.isInteger(value)&&value>0)rows.push({name,address:value>>>0,hex:`0x${(value>>>0).toString(16).padStart(8,'0')}`});}return freeze(rows);}
function parseMapSymbols(text,{max=200000}={}){const rows=[],seen=new Set();for(const raw of String(text||'').split(/\r?\n/)){if(rows.length>=max)break;let address,name;let m=raw.match(/^\s*(0x[0-9a-fA-F]+)\s+(?:0x[0-9a-fA-F]+\s+)?([A-Za-z_.$][\w.$@-]*)\s*$/);if(m){address=Number.parseInt(m[1],16);name=m[2];}else if((m=raw.match(/^\s*\.(?:text|rodata)[.\w$@-]*\s+(0x[0-9a-fA-F]+)\s+(?:0x[0-9a-fA-F]+\s+)?([A-Za-z_.$][\w.$@-]*)?\s*$/))){address=Number.parseInt(m[1],16);name=m[2]||raw.trim().split(/\s+/)[0];}else if((m=raw.match(/^\s*([0-9a-fA-F]{6,16})\s+[TtWw]\s+([A-Za-z_.$][\w.$@-]*)\s*$/))){address=Number.parseInt(m[1],16);name=m[2];}if(!Number.isFinite(address)||!name)continue;const key=`${address}:${name}`;if(seen.has(key))continue;seen.add(key);rows.push({address:address>>>0,name:String(name).slice(0,300)});}rows.sort((a,b)=>a.address-b.address||a.name.localeCompare(b.name));return freeze(rows);}
function resolveMapAddress(symbols,address){if(!Array.isArray(symbols)||!symbols.length||!Number.isInteger(address))return null;let lo=0,hi=symbols.length-1,best=null;while(lo<=hi){const mid=(lo+hi)>>1,row=symbols[mid];if(row.address<=address){best=row;lo=mid+1;}else hi=mid-1;}if(!best)return null;const offset=(address-best.address)>>>0;return freeze({name:best.name,symbolAddress:best.address,offset,address:address>>>0});}
function commandExists(command){const r=spawnSync(process.platform==='win32'?'where':'which',[command],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:5000,windowsHide:true});return r.status===0;}
function resolveAddr2line(requested='auto'){const value=String(requested||'auto').toLowerCase();if(value!=='auto'){if(!ADDR2LINE_TOOLS.includes(value)||!commandExists(value))throw Object.assign(new Error(`${value} is not available for fixed embedded symbolization.`),{code:'EADDR2LINETOOL'});return value;}for(const candidate of ADDR2LINE_TOOLS)if(commandExists(candidate))return candidate;throw Object.assign(new Error(`No supported addr2line tool is available on PATH (${ADDR2LINE_TOOLS.join(', ')}).`),{code:'EADDR2LINETOOL'});}
function addr2lineInvocation(tool,elf,addresses){if(!ADDR2LINE_TOOLS.includes(tool))throw Object.assign(new Error('Unsupported addr2line tool.'),{code:'EADDR2LINETOOL'});return freeze({command:tool,args:['-f','-C','-e',elf,...addresses.map(x=>x.hex)]});}
function boundedText(value,maxBytes=256*1024){const b=Buffer.from(String(value||''),'utf8');return b.length<=maxBytes?{text:b.toString('utf8'),truncated:false}:{text:b.subarray(0,maxBytes).toString('utf8'),truncated:true};}
function portableBasename(value){return String(value||'').replace(/\\/g,'/').split('/').filter(Boolean).at(-1)||'';}
function normalizeDebugLocation(value,cwd=process.cwd()){const raw=String(value||'').trim();if(!raw||raw==='??:0'||raw==='??:?')return raw.slice(0,1000);const m=raw.match(/^(.*):(\d+)(?::(\d+))?$/);if(!m)return raw.replace(String(cwd||''),'<workspace>').slice(0,1000);const file=m[1],line=m[2],column=m[3]?`:${m[3]}`:'',foreignAbsolute=/^[A-Za-z]:[\\/]/.test(file)&&process.platform!=='win32',absolute=path.isAbsolute(file)||/^[A-Za-z]:[\\/]/.test(file);if(!absolute)return `${file.replace(/\\/g,'/')}:${line}${column}`.slice(0,1000);if(!foreignAbsolute){const root=path.resolve(cwd),resolved=path.resolve(file),rel=path.relative(root,resolved);if(rel&&rel!=='..'&&!rel.startsWith(`..${path.sep}`)&&!path.isAbsolute(rel))return `${rel.replace(/\\/g,'/')}:${line}${column}`.slice(0,1000);}return `<external>/${portableBasename(file)}:${line}${column}`.slice(0,1000);}
function symbolizeEmbedded({text='',elfFile='',mapFile='',tool='auto',cwd=process.cwd(),timeoutMs=30000,maxMapBytes=16*1024*1024,maxOutputBytes=256*1024}={}){const addresses=codeAddresses(text);if(!addresses.length)return freeze({status:'no-code-address',addresses:[],map:mapFile?{name:path.basename(mapFile)}:null,elf:elfFile?{name:path.basename(elfFile)}:null,resolutions:[],digest:stableDigest({status:'no-code-address'})});let mapMeta=null,mapRes=[];if(mapFile){const file=boundedRegularFile(mapFile,'linker map',maxMapBytes),content=fs.readFileSync(file.absolute,'utf8'),symbols=parseMapSymbols(content);mapRes=addresses.map(a=>({source:'map',register:a.name,address:a.address,hex:a.hex,resolution:resolveMapAddress(symbols,a.address)}));mapMeta={name:path.basename(file.absolute),size:file.size,symbolCount:symbols.length,digest:stableDigest(content)};}
let elfMeta=null,elfRes=[];if(elfFile){const file=boundedRegularFile(elfFile,'ELF image',512*1024*1024),resolvedTool=resolveAddr2line(tool),inv=addr2lineInvocation(resolvedTool,file.absolute,addresses),run=spawnSync(inv.command,inv.args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:Math.max(1000,Math.min(120000,Number(timeoutMs)||30000)),maxBuffer:Math.max(maxOutputBytes*2,1024*1024),windowsHide:true,env:{...process.env,DEBUGINFOD_URLS:'',DEBUGINFOD_PROGRESS:'0'}});if(run.error&&run.error.code==='ETIMEDOUT')throw Object.assign(new Error(`${resolvedTool} symbolization timed out.`),{code:'EADDR2LINETIMEOUT'});const bounded=boundedText([run.stdout||'',run.stderr||''].filter(Boolean).join('\n'),maxOutputBytes),lines=bounded.text.split(/\r?\n/);for(let i=0;i<addresses.length;i++){const fn=String(lines[i*2]||'').trim(),loc=normalizeDebugLocation(lines[i*2+1]||'',cwd);elfRes.push({source:'elf',register:addresses[i].name,address:addresses[i].address,hex:addresses[i].hex,function:fn.slice(0,500),location:loc});}elfMeta={name:path.basename(file.absolute),size:file.size,tool:resolvedTool,exitCode:Number.isInteger(run.status)?run.status:null,truncated:bounded.truncated,invocationDigest:stableDigest({tool:resolvedTool,args:inv.args.map(v=>path.isAbsolute(v)?path.basename(v):v)}),outputDigest:stableDigest(elfRes)};}
const base={status:'symbolized',addresses,map:mapMeta,elf:elfMeta,resolutions:[...mapRes,...elfRes]};return freeze({...base,digest:stableDigest(base)});}
module.exports={ADDR2LINE_TOOLS,boundedRegularFile,codeAddresses,parseMapSymbols,resolveMapAddress,commandExists,resolveAddr2line,addr2lineInvocation,boundedText,portableBasename,normalizeDebugLocation,symbolizeEmbedded};
