'use strict';

const fs=require('node:fs');
const path=require('node:path');
const {compactFailureLog,classifyFailureDeterministically}=require('./codex-safe-core/diagnosis-platform');
const {DEBUG_EVIDENCE_VERSION,freeze,stableDigest}=require('./contracts');
const {parseFailure}=require('./parsers');
const {collectSourceContext}=require('./source-context');
function readBoundedFile(file,maxBytes=8*1024*1024){const stat=fs.statSync(file);if(!stat.isFile())throw Object.assign(new Error('Failure evidence path must be a regular file.'),{code:'EEVIDENCEFILE'});if(stat.size>maxBytes)throw Object.assign(new Error(`Failure evidence exceeds ${maxBytes} byte limit.`),{code:'EEVIDENCELIMIT'});return fs.readFileSync(file,'utf8');}
function safeSourceLabel(label,workspace){const value=String(label||'inline').slice(0,1024);if(!path.isAbsolute(value))return value.slice(0,512);const rel=path.relative(workspace,value);if(rel&&!rel.startsWith('..')&&!path.isAbsolute(rel))return rel.replace(/\\/g,'/').slice(0,512);return path.basename(value).slice(0,512);}
function buildDebugEvidence({text='',source={},kind='auto',workspace=process.cwd(),git={},commandResult=null,maxCompactBytes=128*1024}={}){const raw=String(text||'');if(!raw.trim())throw Object.assign(new Error('No failure evidence supplied.'),{code:'ENOFAILUREEVIDENCE'});const compact=compactFailureLog(raw,{maxBytes:maxCompactBytes,maxLines:700,contextLines:3}),deterministic=classifyFailureDeterministically(raw),parsed=parseFailure(raw,{kind}),root=git.root||workspace,sourceContext=collectSourceContext(root,parsed.frames),sourceMeta={type:String(source.type||'text'),label:safeSourceLabel(source.label||source.path||'inline',workspace)},command=commandResult?{commandDigest:stableDigest(String(commandResult.command||'')),exitCode:commandResult.exitCode,signal:commandResult.signal||'',timedOut:Boolean(commandResult.timedOut),durationMs:Number(commandResult.durationMs||0)}:null;const workspaceId=stableDigest(path.resolve(workspace));const base={version:DEBUG_EVIDENCE_VERSION,workspaceId,source:sourceMeta,kind:parsed.kind,deterministic,parsed,sourceContext,compact,git:{head:String(git.head||''),rootDigest:git.root?stableDigest(path.resolve(git.root)):'',dirty:Boolean(git.dirty),changedPaths:(git.changedPaths||[]).slice(0,200),recentCommits:(git.recentCommits||[]).slice(0,20)},command};return freeze({...base,digest:stableDigest({workspaceId,source:sourceMeta,kind:parsed.kind,rawDigest:compact.digest,sourceContext:sourceContext.map(v=>({file:v.file,line:v.line,digest:v.digest,blame:v.blame,history:v.history})),git:base.git,command})});}
module.exports={readBoundedFile,safeSourceLabel,buildDebugEvidence};
