'use strict';

const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const {freeze,stableDigest}=require('./contracts');
function git(args,cwd,{allowFailure=false,maxBuffer=2*1024*1024,trim=true}={}){try{const value=execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],maxBuffer});return trim?value.trim():value.replace(/[\r\n]+$/,'');}catch(error){if(allowFailure)return '';throw Object.assign(new Error(`git ${args[0]} failed: ${String(error.stderr||error.message).trim().slice(0,500)}`),{code:'EGIT'});}}
function parseStatusPath(line){let value=String(line||'').length>=3?String(line).slice(3):'';if(value.includes(' -> '))value=value.split(' -> ').at(-1);return value.trim().replace(/^"|"$/g,'').replace(/\\/g,'/');}
function fileState(root,file){const absolute=path.resolve(root,file),relative=path.relative(root,absolute);if(relative.startsWith('..')||path.isAbsolute(relative))return {path:file,state:'outside'};try{const stat=fs.statSync(absolute);if(!stat.isFile())return {path:file,state:'non-file'};const hash=git(['hash-object','--',file],root,{allowFailure:true});return {path:file,state:'file',size:stat.size,hash:/^[0-9a-f]{40}$/.test(hash)?hash:''};}catch{return {path:file,state:'missing'};}}
function collectGitContext(workspace,{includeHistory=true}={}){const root=git(['rev-parse','--show-toplevel'],workspace,{allowFailure:true});if(!root)return freeze({root:'',head:'',dirty:false,changedPaths:[],recentCommits:[],stateFingerprint:''});const head=git(['rev-parse','HEAD'],root,{allowFailure:true});const status=git(['status','--porcelain=v1','--untracked-files=all'],root,{allowFailure:true,trim:false});const changedPaths=[...new Set(status.split(/\r?\n/).filter(Boolean).map(parseStatusPath).filter(Boolean))].slice(0,200),states=changedPaths.map(file=>fileState(root,file));let recentCommits=[];if(includeHistory){const raw=git(['log','-n','20','--date=iso-strict','--pretty=format:%H%x09%ad%x09%s'],root,{allowFailure:true});recentCommits=raw.split(/\r?\n/).filter(Boolean).map(line=>{const [sha,date,...subject]=line.split('\t');return {sha,date,subject:subject.join('\t').slice(0,300)};});}return freeze({root,head,dirty:Boolean(status),changedPaths,recentCommits,stateFingerprint:stableDigest({head,states})});}
function collectFileHistory(workspace,file,{max=12}={}){const raw=git(['log','-n',String(max),'--pretty=format:%H%x09%ad%x09%s','--date=iso-strict','--',file],workspace,{allowFailure:true});return freeze(raw.split(/\r?\n/).filter(Boolean).map(line=>{const [sha,date,...subject]=line.split('\t');return {sha,date,subject:subject.join('\t').slice(0,300)};}));}
module.exports={git,parseStatusPath,fileState,collectGitContext,collectFileHistory};
