'use strict';

const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const {freeze,stableDigest}=require('./contracts');
function git(args,cwd,{allowFailure=false,maxBuffer=2*1024*1024,trim=true}={}){try{const value=execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],maxBuffer});return trim?value.trim():value;}catch(error){if(allowFailure)return '';throw Object.assign(new Error(`git ${args[0]} failed: ${String(error.stderr||error.message).trim().slice(0,500)}`),{code:'EGIT'});}}
function normalizeGitPath(value){return String(value||'').replace(/\\/g,'/');}
function parsePorcelainZ(raw){const parts=String(raw||'').split('\0'),rows=[];for(let i=0;i<parts.length;i++){const record=parts[i];if(!record||record.length<4)continue;const xy=record.slice(0,2),file=normalizeGitPath(record.slice(3));if(file)rows.push({xy,path:file});if(/[RC]/.test(xy))i++;}return rows;}
function parseStatusPath(line){let value=String(line||'').length>=3?String(line).slice(3):'';if(value.includes(' -> '))value=value.split(' -> ').at(-1);return normalizeGitPath(value.trim().replace(/^"|"$/g,''));}
function isInternalDebugPath(file){const value=normalizeGitPath(file);return value==='.codex-debug'||value.startsWith('.codex-debug/');}
function gitlinkState(root,file,absolute){const staged=git(['ls-files','--stage','--',file],root,{allowFailure:true});if(!/^160000\s+[0-9a-f]{40}\s+\d+\t/.test(staged))return null;const head=git(['rev-parse','HEAD'],absolute,{allowFailure:true}),status=git(['status','--porcelain=v1','-z','--untracked-files=all'],absolute,{allowFailure:true,trim:false});return {path:file,state:'gitlink',head:/^[0-9a-f]{40}$/.test(head)?head:'',dirtyDigest:stableDigest(status)};}
function fileState(root,file){const normalized=normalizeGitPath(file),absolute=path.resolve(root,normalized),relative=normalizeGitPath(path.relative(root,absolute));if(relative.startsWith('../')||relative==='..'||path.isAbsolute(relative))return {path:normalized,state:'outside'};try{const stat=fs.lstatSync(absolute);if(stat.isSymbolicLink())return {path:normalized,state:'symlink',targetDigest:stableDigest(fs.readlinkSync(absolute))};if(stat.isDirectory())return gitlinkState(root,normalized,absolute)||{path:normalized,state:'directory'};if(!stat.isFile())return {path:normalized,state:'non-file'};const hash=git(['hash-object','--',normalized],root,{allowFailure:true});return {path:normalized,state:'file',size:stat.size,hash:/^[0-9a-f]{40}$/.test(hash)?hash:''};}catch{return {path:normalized,state:'missing'};}}
function collectGitContext(workspace,{includeHistory=true}={}){const root=git(['rev-parse','--show-toplevel'],workspace,{allowFailure:true});if(!root)return freeze({root:'',head:'',dirty:false,changedPaths:[],recentCommits:[],stateFingerprint:''});const head=git(['rev-parse','HEAD'],root,{allowFailure:true}),status=git(['status','--porcelain=v1','-z','--untracked-files=all'],root,{allowFailure:true,trim:false}),rows=parsePorcelainZ(status).filter(row=>row.path&&!isInternalDebugPath(row.path)),changedPaths=[...new Set(rows.map(row=>row.path))].slice(0,200),states=changedPaths.map(file=>fileState(root,file));let recentCommits=[];if(includeHistory){const raw=git(['log','-n','20','--date=iso-strict','--pretty=format:%H%x09%ad%x09%s'],root,{allowFailure:true});recentCommits=raw.split(/\r?\n/).filter(Boolean).map(line=>{const [sha,date,...subject]=line.split('\t');return {sha,date,subject:subject.join('\t').slice(0,300)};});}return freeze({root,head,dirty:rows.length>0,changedPaths,recentCommits,stateFingerprint:stableDigest({head,states})});}
function collectFileHistory(workspace,file,{max=12}={}){const raw=git(['log','-n',String(max),'--pretty=format:%H%x09%ad%x09%s','--date=iso-strict','--',file],workspace,{allowFailure:true});return freeze(raw.split(/\r?\n/).filter(Boolean).map(line=>{const [sha,date,...subject]=line.split('\t');return {sha,date,subject:subject.join('\t').slice(0,300)};}));}
module.exports={git,normalizeGitPath,parsePorcelainZ,parseStatusPath,isInternalDebugPath,gitlinkState,fileState,collectGitContext,collectFileHistory};
