'use strict';

const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {freeze}=require('./contracts');
function extractPatchPaths(patch){const out=new Set();for(const line of String(patch||'').split(/\r?\n/)){const m=line.match(/^diff --git a\/(.+) b\/(.+)$/);if(m){out.add(m[1]);out.add(m[2]);continue;}const f=line.match(/^(?:---|\+\+\+)\s+(?:[ab]\/)?([^\t ]+)/);if(f&&f[1]!=='/dev/null')out.add(f[1]);}return [...out];}
function validatePatch(patch,{maxBytes=256*1024}={}){const text=String(patch||'');if(!text.trim())throw Object.assign(new Error('No patch was proposed.'),{code:'ENOPATCH'});if(Buffer.byteLength(text,'utf8')>maxBytes)throw Object.assign(new Error('Patch exceeds bounded size.'),{code:'EPATCHLIMIT'});if(/GIT binary patch|Binary files .* differ/.test(text))throw Object.assign(new Error('Binary patches are not allowed.'),{code:'EPATCHBINARY'});const paths=extractPatchPaths(text);if(!paths.length)throw Object.assign(new Error('Patch contains no file paths.'),{code:'EPATCHFORMAT'});for(const p of paths){const normalized=p.replace(/\\/g,'/');if(path.posix.isAbsolute(normalized)||normalized.split('/').includes('..')||normalized==='.git'||normalized.startsWith('.git/')||normalized==='src/codex-safe-core'||normalized.startsWith('src/codex-safe-core/'))throw Object.assign(new Error(`Unsafe patch path: ${p}`),{code:'EPATCHPATH'});}return freeze({text,paths:Object.freeze(paths)});}
function gitApply(patch,{cwd=process.cwd(),apply=false}={}){const validated=validatePatch(patch);const check=spawnSync('git',['apply','--check','--whitespace=error-all','-'],{cwd,input:validated.text,encoding:'utf8',windowsHide:true});if(check.status!==0)throw Object.assign(new Error(`Patch validation failed: ${String(check.stderr||check.stdout||'git apply --check failed').trim().slice(0,1000)}`),{code:'EPATCHCHECK'});if(!apply)return freeze({checked:true,applied:false,paths:validated.paths});const result=spawnSync('git',['apply','--whitespace=error-all','-'],{cwd,input:validated.text,encoding:'utf8',windowsHide:true});if(result.status!==0)throw Object.assign(new Error(`Patch apply failed: ${String(result.stderr||result.stdout||'git apply failed').trim().slice(0,1000)}`),{code:'EPATCHAPPLY'});return freeze({checked:true,applied:true,paths:validated.paths});}
module.exports={extractPatchPaths,validatePatch,gitApply};
