'use strict';

const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {freeze}=require('./contracts');
const PROTECTED_PATCH_PATHS=Object.freeze([/^(?:\.github\/workflows|\.github\/actions)(?:\/|$)/i,/^(?:CODEOWNERS|\.github\/CODEOWNERS|docs\/CODEOWNERS)$/i,/^\.gitmodules$/i,/(?:^|\/)\.env(?:\.|$)/i,/(?:^|\/)[^/]+\.(?:pem|key|p12|pfx)$/i,/^(?:vendor|third_party|node_modules|generated|dist|build|out|coverage)(?:\/|$)/i,/(?:^|\/)(?:vendor|third_party|generated)(?:\/|$)/i]);
function validatePatchText(patch,{maxBytes=256*1024}={}){const text=String(patch||'');if(!text.trim())throw Object.assign(new Error('No patch was proposed.'),{code:'ENOPATCH'});if(Buffer.byteLength(text,'utf8')>maxBytes)throw Object.assign(new Error('Patch exceeds bounded size.'),{code:'EPATCHLIMIT'});if(/GIT binary patch|Binary files .* differ/.test(text))throw Object.assign(new Error('Binary patches are not allowed.'),{code:'EPATCHBINARY'});if(/^(?:rename|copy) (?:from|to) /m.test(text))throw Object.assign(new Error('Rename/copy patches are not allowed in the current rollback contract.'),{code:'EPATCHRENAME'});return text;}
function parseNumstatZ(raw){const paths=[];for(const record of String(raw||'').split('\0')){if(!record)continue;const first=record.indexOf('\t'),second=first>=0?record.indexOf('\t',first+1):-1;if(first<0||second<0)throw Object.assign(new Error('Git returned malformed patch numstat.'),{code:'EPATCHFORMAT'});const file=record.slice(second+1);if(file)paths.push(file.replace(/\\/g,'/'));}return [...new Set(paths)];}
function extractPatchPaths(patch,{cwd=process.cwd(),maxBytes=256*1024}={}){const text=validatePatchText(patch,{maxBytes}),parsed=spawnSync('git',['apply','--numstat','-z','-'],{cwd,input:text,encoding:'utf8',windowsHide:true,maxBuffer:1024*1024});if(parsed.error)throw Object.assign(new Error(`Unable to parse patch paths with Git: ${parsed.error.message}`),{code:'EPATCHPARSER'});if(parsed.status!==0){const detail=String(parsed.stderr||parsed.stdout||'invalid patch').trim().slice(0,1000);if(/invalid path|outside repository|\.git[/\\]|path traversal/i.test(detail))throw Object.assign(new Error(`Unsafe patch path rejected by Git: ${detail}`),{code:'EPATCHPATH'});throw Object.assign(new Error(`Git could not parse patch paths: ${detail}`),{code:'EPATCHFORMAT'});}const paths=parseNumstatZ(parsed.stdout);if(!paths.length)throw Object.assign(new Error('Patch contains no file paths.'),{code:'EPATCHFORMAT'});return paths;}
function validatePath(p){const normalized=String(p||'').replace(/\\/g,'/');if(!normalized||path.posix.isAbsolute(normalized)||normalized.split('/').includes('..')||normalized==='.git'||normalized.startsWith('.git/')||normalized==='.codex-debug'||normalized.startsWith('.codex-debug/')||normalized==='src/codex-safe-core'||normalized.startsWith('src/codex-safe-core/'))throw Object.assign(new Error(`Unsafe patch path: ${p}`),{code:'EPATCHPATH'});if(PROTECTED_PATCH_PATHS.some(re=>re.test(normalized)))throw Object.assign(new Error(`Protected/generated/vendor patch path is not eligible for model apply: ${p}`),{code:'EPATCHPROTECTED'});return normalized;}
function validatePatch(patch,{cwd=process.cwd(),maxBytes=256*1024}={}){const text=validatePatchText(patch,{maxBytes}),paths=extractPatchPaths(text,{cwd,maxBytes}).map(validatePath);return freeze({text,paths:Object.freeze(paths)});}
function gitApply(patch,{cwd=process.cwd(),apply=false}={}){const validated=validatePatch(patch,{cwd});const check=spawnSync('git',['apply','--check','--whitespace=error-all','-'],{cwd,input:validated.text,encoding:'utf8',windowsHide:true});if(check.status!==0)throw Object.assign(new Error(`Patch validation failed: ${String(check.stderr||check.stdout||'git apply --check failed').trim().slice(0,1000)}`),{code:'EPATCHCHECK'});if(!apply)return freeze({checked:true,applied:false,paths:validated.paths});const result=spawnSync('git',['apply','--whitespace=error-all','-'],{cwd,input:validated.text,encoding:'utf8',windowsHide:true});if(result.status!==0)throw Object.assign(new Error(`Patch apply failed: ${String(result.stderr||result.stdout||'git apply failed').trim().slice(0,1000)}`),{code:'EPATCHAPPLY'});return freeze({checked:true,applied:true,paths:validated.paths});}
module.exports={PROTECTED_PATCH_PATHS,validatePatchText,parseNumstatZ,extractPatchPaths,validatePath,validatePatch,gitApply};
