'use strict';
const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');const {freeze,stableDigest}=require('./contracts');const {parsePlatformEvidence,baseName}=require('./platform-evidence');const {commandExists,compileSourcePrefixMaps,normalizeDebugLocation}=require('./embedded-symbols');
const READELF_TOOLS=Object.freeze(['llvm-readelf','readelf']),HOST_ADDR2LINE_TOOLS=Object.freeze(['llvm-addr2line','addr2line']);
function platformFile(file,label,maxBytes=512*1024*1024){const absolute=path.resolve(String(file||''));if(!file)throw Object.assign(new Error(`${label} is required.`),{code:'EPLATFORMSYMBOLINPUT'});const stat=fs.lstatSync(absolute);if(stat.isSymbolicLink()||!stat.isFile())throw Object.assign(new Error(`${label} must be a regular non-symlink file.`),{code:'EPLATFORMSYMBOLINPUT'});if(stat.size>maxBytes)throw Object.assign(new Error(`${label} exceeds ${maxBytes} bytes.`),{code:'EPLATFORMSYMBOLLIMIT'});return {absolute,size:stat.size,mtimeMs:Math.floor(stat.mtimeMs)};}
function sha256File(file){const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),buffer=Buffer.allocUnsafe(1024*1024);try{for(;;){const n=fs.readSync(fd,buffer,0,buffer.length,null);if(!n)break;h.update(buffer.subarray(0,n));}}finally{fs.closeSync(fd);}return h.digest('hex');}
function resolveFixedTool(requested,choices,label,code){const value=String(requested||'auto').toLowerCase();if(value!=='auto'){if(!choices.includes(value)||!commandExists(value))throw Object.assign(new Error(`${value} is not available for fixed ${label}.`),{code});return value;}for(const candidate of choices)if(commandExists(candidate))return candidate;throw Object.assign(new Error(`No supported ${label} tool is available on PATH (${choices.join(', ')}).`),{code});}
function resolveReadelf(requested='auto'){return resolveFixedTool(requested,READELF_TOOLS,'ELF BuildId inspection','EREADELFTOOL');}
function resolveHostAddr2line(requested='auto'){return resolveFixedTool(requested,HOST_ADDR2LINE_TOOLS,'host addr2line','EHOSTADDR2LINE');}
function elfBuildId(file,{tool='auto',cwd=process.cwd(),timeoutMs=30000}={}){const resolved=resolveReadelf(tool),run=spawnSync(resolved,['-n',file],{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:Math.max(1000,Math.min(120000,Number(timeoutMs)||30000)),maxBuffer:2*1024*1024,windowsHide:true,env:{...process.env,DEBUGINFOD_URLS:'',DEBUGINFOD_PROGRESS:'0'}});if(run.error&&run.error.code==='ETIMEDOUT')throw Object.assign(new Error(`${resolved} BuildId inspection timed out.`),{code:'EREADELFTIMEOUT'});const text=[run.stdout||'',run.stderr||''].join('\n'),m=text.match(/Build ID:\s*([0-9a-f]+)/i);return freeze({tool:resolved,buildId:String(m?.[1]||'').toLowerCase(),exitCode:Number.isInteger(run.status)?run.status:null,outputDigest:stableDigest(text.slice(0,2*1024*1024))});}
function parseAndroidSymbolSpec(spec,cwd=process.cwd()){const raw=String(spec||'');if(!raw||raw.length>4096||raw.includes('\0'))throw Object.assign(new Error('Invalid Android symbol mapping.'),{code:'EANDROIDSYMBOL'});const split=raw.indexOf('=');if(split<=0||split===raw.length-1)throw Object.assign(new Error('Android symbol mapping must use MODULE=ELF.'),{code:'EANDROIDSYMBOL'});const module=raw.slice(0,split).trim().replace(/\\/g,'/'),file=platformFile(path.resolve(cwd,raw.slice(split+1).trim()),'Android symbol ELF');if(!module)throw Object.assign(new Error('Android symbol MODULE is required.'),{code:'EANDROIDSYMBOL'});return {module,moduleBase:baseName(module),file:file.absolute,size:file.size,mtimeMs:file.mtimeMs,fileDigest:sha256File(file.absolute)};}
function compileAndroidSymbolSpecs(specs,cwd=process.cwd()){if((specs||[]).length>12)throw Object.assign(new Error('At most 12 Android symbol mappings are allowed.'),{code:'EANDROIDSYMBOL'});const rows=[],seen=new Set();for(const raw of specs||[]){const row=parseAndroidSymbolSpec(raw,cwd),key=row.module.toLowerCase();if(seen.has(key))throw Object.assign(new Error(`Duplicate Android symbol mapping: ${row.module}`),{code:'EANDROIDSYMBOL'});seen.add(key);rows.push(row);}return freeze(rows);}
function safeAndroidSpec(row){return freeze({moduleBase:row.moduleBase,fileName:path.basename(row.file),size:row.size,fileDigest:row.fileDigest});}
function findAndroidSpec(frame,specs){const module=String(frame?.module||'').replace(/\\/g,'/').toLowerCase(),moduleBase=baseName(module).toLowerCase();return (specs||[]).find(row=>row.module.toLowerCase()===module)||(specs||[]).find(row=>row.moduleBase.toLowerCase()===moduleBase)||null;}
function boundedPairOutput(run){const text=[run.stdout||'',run.stderr||''].filter(Boolean).join('\n'),buffer=Buffer.from(text,'utf8'),bounded=buffer.length<=256*1024?buffer:buffer.subarray(0,256*1024);return bounded.toString('utf8');}
function symbolizeAndroid({android,symbolSpecs=[],cwd=process.cwd(),sourcePrefixMaps=[],addr2line='auto',readelf='auto',timeoutMs=30000}={}){if(!android?.frames?.length||!(symbolSpecs||[]).length)return null;const specs=compileAndroidSymbolSpecs(symbolSpecs,cwd),maps=compileSourcePrefixMaps(sourcePrefixMaps,cwd),safeMaps=maps.map(row=>({fromDigest:stableDigest(row.from),target:row.targetRelative})),buildIds=new Map(),tool=resolveHostAddr2line(addr2line),resolutions=[];for(const frame of android.frames.slice(0,50)){const spec=findAndroidSpec(frame,specs);if(!spec){resolutions.push({frameIndex:frame.index,module:frame.module,pc:frame.pc,status:'symbol-file-missing'});continue;}let identity=buildIds.get(spec.file);if(!identity){identity=elfBuildId(spec.file,{tool:readelf,cwd,timeoutMs});buildIds.set(spec.file,identity);}const expected=String(frame.buildId||'').toLowerCase(),actual=String(identity.buildId||'').toLowerCase(),safeSpec=safeAndroidSpec(spec);if(!expected){resolutions.push({frameIndex:frame.index,module:frame.module,moduleBase:frame.moduleBase,pc:frame.pc,expectedBuildId:'',actualBuildId:actual,status:'build-id-missing',symbolFile:safeSpec});continue;}if(!actual){resolutions.push({frameIndex:frame.index,module:frame.module,moduleBase:frame.moduleBase,pc:frame.pc,expectedBuildId:expected,actualBuildId:'',status:'build-id-unavailable',symbolFile:safeSpec});continue;}if(expected!==actual){resolutions.push({frameIndex:frame.index,module:frame.module,moduleBase:frame.moduleBase,pc:frame.pc,expectedBuildId:expected,actualBuildId:actual,status:'build-id-mismatch',symbolFile:safeSpec});continue;}const address=`0x${String(frame.pc||'0').replace(/^0x/i,'')}`,run=spawnSync(tool,['-f','-C','-e',spec.file,address],{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:Math.max(1000,Math.min(120000,Number(timeoutMs)||30000)),maxBuffer:512*1024,windowsHide:true,env:{...process.env,DEBUGINFOD_URLS:'',DEBUGINFOD_PROGRESS:'0'}}),output=boundedPairOutput(run),lines=output.split(/\r?\n/),fn=String(lines[0]||'').trim(),location=normalizeDebugLocation(lines[1]||'',cwd,maps),ok=Number.isInteger(run.status)&&run.status===0&&fn&&fn!=='??'&&location&&location!=='??:0'&&location!=='??:?';resolutions.push({frameIndex:frame.index,module:frame.module,moduleBase:frame.moduleBase,pc:frame.pc,expectedBuildId:expected,actualBuildId:actual,buildIdMatch:true,function:fn.slice(0,500),location,status:ok?'resolved':'symbolizer-failed',symbolFile:safeSpec,outputDigest:stableDigest(output)});}const base={tool,sourcePrefixMaps:safeMaps,symbolFiles:specs.map(safeAndroidSpec),resolutions};return freeze({...base,digest:stableDigest(base)});}
function parseSystemMap(text,{max=750000}={}){const rows=[],seen=new Set();for(const raw of String(text||'').split(/\r?\n/)){if(rows.length>=max)break;const m=raw.match(/^\s*([0-9a-fA-F]{8,16})\s+([A-Za-z])\s+(\S+)/);if(!m)continue;const address=m[1].toLowerCase(),symbol=m[3].slice(0,500),key=`${address}:${symbol}`;if(seen.has(key))continue;seen.add(key);rows.push({address,type:m[2],symbol});}rows.sort((a,b)=>{const aa=BigInt(`0x${a.address}`),bb=BigInt(`0x${b.address}`);return aa<bb?-1:aa>bb?1:a.symbol.localeCompare(b.symbol);});return freeze(rows);}
function resolveSystemMapAddress(symbols,address){const raw=String(address||'').replace(/^0x/i,'').toLowerCase();if(!/^[0-9a-f]{8,16}$/.test(raw)||!Array.isArray(symbols)||!symbols.length)return null;const target=BigInt(`0x${raw}`);let lo=0,hi=symbols.length-1,best=null;while(lo<=hi){const mid=(lo+hi)>>1,row=symbols[mid],value=BigInt(`0x${row.address}`);if(value<=target){best=row;lo=mid+1;}else hi=mid-1;}if(!best)return null;const offset=target-BigInt(`0x${best.address}`);return freeze({address:raw,symbol:best.symbol,symbolAddress:best.address,offsetHex:`0x${offset.toString(16)}`});}
function resolveKernelSystemMap({kernel,systemMapFile}={}){if(!kernel||!systemMapFile)return null;const file=platformFile(systemMapFile,'Kernel System.map',64*1024*1024),content=fs.readFileSync(file.absolute,'utf8'),symbols=parseSystemMap(content),pc=resolveSystemMapAddress(symbols,kernel.pcAddress),frames=(kernel.callTrace||[]).slice(0,50).map(frame=>({address:frame.address||'',symbolFromLog:frame.symbol,module:frame.module||'',resolution:frame.module?null:resolveSystemMapAddress(symbols,frame.address),status:frame.module?'module-map-required':frame.address?'resolved-or-below':'address-missing'})),meta={name:path.basename(file.absolute),size:file.size,fileDigest:sha256File(file.absolute),symbolCount:symbols.length};const base={systemMap:meta,pc,frames};return freeze({...base,digest:stableDigest(base)});}
function symbolizePlatform({text='',androidSymbolSpecs=[],kernelSystemMap='',cwd=process.cwd(),sourcePrefixMaps=[],addr2line='auto',readelf='auto',timeoutMs=30000}={}){const parsed=parsePlatformEvidence(text),android=symbolizeAndroid({android:parsed.android,symbolSpecs:androidSymbolSpecs,cwd,sourcePrefixMaps,addr2line,readelf,timeoutMs}),kernel=kernelSystemMap?resolveKernelSystemMap({kernel:parsed.kernel,systemMapFile:path.resolve(cwd,kernelSystemMap)}):null,base={android,kernel};return android||kernel?freeze({...base,digest:stableDigest(base)}):null;}
module.exports={READELF_TOOLS,HOST_ADDR2LINE_TOOLS,platformFile,sha256File,resolveFixedTool,resolveReadelf,resolveHostAddr2line,elfBuildId,parseAndroidSymbolSpec,compileAndroidSymbolSpecs,safeAndroidSpec,findAndroidSpec,symbolizeAndroid,parseSystemMap,resolveSystemMapAddress,resolveKernelSystemMap,symbolizePlatform};
