'use strict';

const fs=require('node:fs');
const path=require('node:path');
function sessionDirectory(workspace){return path.join(path.resolve(workspace),'.codex-debug','sessions');}
function safeSessionId(value){const id=String(value||'');if(!/^dbg-[0-9a-f]{16}$/.test(id))throw Object.assign(new Error('Invalid Debug session id.'),{code:'ESESSIONID'});return id;}
function assertPrivateDirectory(root,dir){const resolvedRoot=path.resolve(root),resolved=path.resolve(dir),relative=path.relative(resolvedRoot,resolved);if(relative.startsWith('..')||path.isAbsolute(relative))throw Object.assign(new Error('Debug session directory escaped workspace root.'),{code:'ESESSIONPATH'});let current=resolvedRoot;for(const part of relative.split(path.sep).filter(Boolean)){current=path.join(current,part);try{const stat=fs.lstatSync(current);if(stat.isSymbolicLink())throw Object.assign(new Error(`Debug session directory must not traverse a symlink/junction: ${current}`),{code:'ESESSIONPATH'});if(!stat.isDirectory())throw Object.assign(new Error(`Debug session directory component is not a directory: ${current}`),{code:'ESESSIONPATH'});}catch(error){if(error.code==='ENOENT'){fs.mkdirSync(current,{mode:0o700});continue;}throw error;}}return resolved;}
function writeSession(workspace,session){const root=path.resolve(workspace),dir=assertPrivateDirectory(root,sessionDirectory(root));const target=path.join(dir,`${safeSessionId(session.sessionId)}.json`);if(fs.existsSync(target))throw Object.assign(new Error(`Debug session already exists; refusing to overwrite: ${session.sessionId}`),{code:'ESESSIONCOLLISION'});const temp=path.join(dir,`.${session.sessionId}.${process.pid}.${Date.now()}.tmp`),payload=`${JSON.stringify(session,null,2)}\n`;try{fs.writeFileSync(temp,payload,{encoding:'utf8',mode:0o600,flag:'wx'});fs.linkSync(temp,target);try{fs.chmodSync(target,0o600);}catch{}}catch(error){if(error.code==='EEXIST')throw Object.assign(new Error(`Debug session already exists; refusing to overwrite: ${session.sessionId}`),{code:'ESESSIONCOLLISION'});throw error;}finally{try{fs.unlinkSync(temp);}catch{}}return target;}
function readSession(workspace,sessionId){const root=path.resolve(workspace),dir=assertPrivateDirectory(root,sessionDirectory(root)),file=path.join(dir,`${safeSessionId(sessionId)}.json`);const stat=fs.lstatSync(file);if(stat.isSymbolicLink()||!stat.isFile()||stat.nlink>1)throw Object.assign(new Error('Debug session file must be a single-link regular file.'),{code:'ESESSIONPATH'});return JSON.parse(fs.readFileSync(file,'utf8'));}
function listSessions(workspace,{max=50}={}){const root=path.resolve(workspace);let dir;try{dir=assertPrivateDirectory(root,sessionDirectory(root));return fs.readdirSync(dir).filter(v=>/^dbg-[0-9a-f]{16}\.json$/.test(v)).map(v=>{const file=path.join(dir,v),stat=fs.lstatSync(file);if(stat.isSymbolicLink()||!stat.isFile()||stat.nlink>1)return null;return {sessionId:v.slice(0,-5),mtimeMs:stat.mtimeMs};}).filter(Boolean).sort((a,b)=>b.mtimeMs-a.mtimeMs).slice(0,max);}catch{return [];}}
module.exports={sessionDirectory,safeSessionId,assertPrivateDirectory,writeSession,readSession,listSessions};
