'use strict';

const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {freeze,stableDigest}=require('./contracts');
function regularFile(value,label){const file=path.resolve(String(value||''));if(!value)throw Object.assign(new Error(`${label} is required.`),{code:'ESYMBOLINPUT'});const stat=fs.lstatSync(file);if(stat.isSymbolicLink()||!stat.isFile())throw Object.assign(new Error(`${label} must be a regular non-symlink file.`),{code:'ESYMBOLINPUT'});return {file,size:stat.size,mtimeMs:Math.floor(stat.mtimeMs)};}
function commandExists(command){const probe=spawnSync(process.platform==='win32'?'where':'which',[command],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:5000,windowsHide:true});return probe.status===0;}
function resolveDebugger(requested='auto'){const value=String(requested||'auto').toLowerCase();if(value!=='auto'){if(!['gdb','lldb'].includes(value))throw Object.assign(new Error('Debugger must be auto|gdb|lldb.'),{code:'ESYMBOLTOOL'});if(!commandExists(value))throw Object.assign(new Error(`${value} is not available on PATH.`),{code:'ESYMBOLTOOL'});return value;}for(const candidate of ['gdb','lldb'])if(commandExists(candidate))return candidate;throw Object.assign(new Error('Neither gdb nor lldb is available on PATH.'),{code:'ESYMBOLTOOL'});}
function debuggerInvocation(tool,executable,core){if(tool==='gdb')return {command:'gdb',args:['-nx','-nh','-batch','-iex','set auto-load off','-iex','set debuginfod enabled off','-ex','set pagination off','-ex','set confirm off','-ex','thread apply all bt 32',executable,core]};return {command:'lldb',args:['--no-lldbinit','--batch','-O','settings set target.load-script-from-symbol-file false','--core',core,executable,'-o','thread backtrace all -c 32']};}
function boundedOutput(value,maxBytes){const buffer=Buffer.from(String(value||''),'utf8');if(buffer.length<=maxBytes)return {text:buffer.toString('utf8'),truncated:false};let end=maxBytes;while(end>0&&(buffer[end]&0xc0)===0x80)end--;return {text:buffer.subarray(0,end).toString('utf8'),truncated:true};}
function escapeRegex(value){return String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function pathVariants(value){const raw=String(value||'');return [...new Set([raw,raw.replace(/\\/g,'/'),raw.replace(/\//g,'\\')].filter(Boolean))].sort((a,b)=>b.length-a.length);}
function sanitizeDebuggerOutput(value,{cwd=process.cwd(),home=os.homedir(),coreFile='',executable=''}={}){let text=String(value||'');for(const file of [coreFile,executable])for(const variant of pathVariants(file))text=text.replace(new RegExp(escapeRegex(variant),'gi'),path.basename(file));const workspace=path.resolve(cwd);if(workspace!==path.parse(workspace).root){for(const variant of pathVariants(workspace)){const escaped=escapeRegex(variant);text=text.replace(new RegExp(`${escaped}[\\\\/]`,'gi'),'');text=text.replace(new RegExp(escaped,'gi'),'<workspace>');}}const homePath=home?path.resolve(home):'';if(homePath&&homePath!==path.parse(homePath).root){for(const variant of pathVariants(homePath)){const escaped=escapeRegex(variant);text=text.replace(new RegExp(`${escaped}[\\\\/]`,'gi'),'<home>/');text=text.replace(new RegExp(escaped,'gi'),'<home>');}}return text;}
function symbolizeCore({coreFile,executable,tool='auto',cwd=process.cwd(),timeoutMs=120000,maxBytes=1024*1024}={}){const core=regularFile(coreFile,'core file'),exe=regularFile(executable,'executable'),resolved=resolveDebugger(tool),invocation=debuggerInvocation(resolved,exe.file,core.file),result=spawnSync(invocation.command,invocation.args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:Math.max(1000,Math.min(600000,Number(timeoutMs)||120000)),maxBuffer:Math.max(maxBytes*2,2*1024*1024),windowsHide:true,env:{...process.env,DEBUGINFOD_URLS:'',DEBUGINFOD_PROGRESS:'0',GDBHISTFILE:process.platform==='win32'?'NUL':'/dev/null'}}),combined=[result.stdout||'',result.stderr||''].filter(Boolean).join('\n'),sanitized=sanitizeDebuggerOutput(combined,{cwd,coreFile:core.file,executable:exe.file}),bounded=boundedOutput(sanitized,Math.max(4096,Math.min(4*1024*1024,Number(maxBytes)||1024*1024)));if(result.error&&result.error.code==='ETIMEDOUT')throw Object.assign(new Error(`${resolved} symbolization timed out.`),{code:'ESYMBOLTIMEOUT'});if(!bounded.text.trim())throw Object.assign(new Error(`${resolved} produced no symbolization output.`),{code:'ESYMBOLOUTPUT'});return freeze({tool:resolved,exitCode:Number.isInteger(result.status)?result.status:null,signal:result.signal||'',text:bounded.text,truncated:bounded.truncated,core:{name:path.basename(core.file),size:core.size,mtimeMs:core.mtimeMs},executable:{name:path.basename(exe.file),size:exe.size,mtimeMs:exe.mtimeMs},invocationDigest:stableDigest({tool:resolved,args:invocation.args.map(v=>path.isAbsolute(v)?path.basename(v):v)}),outputDigest:stableDigest(bounded.text)});}
module.exports={regularFile,resolveDebugger,debuggerInvocation,boundedOutput,sanitizeDebuggerOutput,symbolizeCore};
